import { BcdrTopology } from "./bcdr.models"

export const BCDR_TOPOLOGIES: BcdrTopology[] = [
  {
    id: "active-passive-dr",
    name: "Active Passive DR",
    summary:
      "The enterprise workload stays on the primary application while synchronized replication keeps the recovery site ready to take over if the primary site fails.",
    defaultPolicyId: "protect-primary",
    policies: [
      {
        id: "protect-primary",
        label: "Protect primary",
        summary:
          "Keep the primary application active while maintaining synchronized recovery readiness at the secondary site.",
        strategy: "active-passive",
        priority: 1,
      },
      {
        id: "promote-recovery",
        label: "Promote recovery",
        summary:
          "Favor continuity through the recovery application when the primary path becomes unavailable or risk exceeds tolerance.",
        strategy: "active-active",
        priority: 2,
      },
    ],
    devices: [
      {
        id: "hq-user",
        label: "HQ User",
        kind: "enterprise-client",
        status: "online",
        x: 120,
        y: 280,
        detail: "Enterprise user initiating traffic toward the line-of-business application.",
        site: "HQ Campus",
        region: "Primary Campus",
        tier: "branch",
        role: "source",
        domain: "enterprise-edge",
        rack: "HQ-1",
      },
      {
        id: "hq-gateway",
        label: "HQ Gateway",
        kind: "branch-gateway",
        status: "online",
        x: 300,
        y: 280,
        detail:
          "Branch transport gateway connecting users to primary and recovery application paths.",
        site: "HQ Campus",
        region: "Primary Campus",
        tier: "transport",
        role: "gateway",
        domain: "transport",
        rack: "GW-1",
      },
      {
        id: "primary-erp",
        label: "Primary ERP",
        kind: "primary-app",
        status: "online",
        x: 520,
        y: 200,
        detail: "Primary enterprise application serving production traffic.",
        site: "Primary DC",
        region: "East Region",
        tier: "application",
        role: "primary",
        domain: "business-app",
        syncState: "synchronized",
        rack: "APP-1",
        cluster: "erp-primary",
      },
      {
        id: "recovery-erp",
        label: "Recovery ERP",
        kind: "recovery-app",
        status: "online",
        x: 760,
        y: 320,
        detail: "Warm recovery application ready for continuity if the primary site is lost.",
        site: "Recovery DC",
        region: "West Region",
        tier: "application",
        role: "recovery",
        domain: "business-app",
        syncState: "synchronized",
        rack: "APP-2",
        cluster: "erp-recovery",
      },
      {
        id: "replication-controller",
        label: "Replication Controller",
        kind: "replication-controller",
        status: "online",
        x: 520,
        y: 60,
        detail: "Continuity controller tracking recovery strategy and replica freshness.",
        site: "Operations Core",
        region: "Control Plane",
        tier: "control",
        role: "controller",
        domain: "continuity-control",
        rack: "CTRL-1",
      },
      {
        id: "vault-storage",
        label: "Vault Storage",
        kind: "data-vault",
        status: "online",
        x: 760,
        y: 120,
        detail: "Data vault retaining synchronized backups and replica snapshots.",
        site: "Recovery DC",
        region: "West Region",
        tier: "storage",
        role: "storage",
        domain: "recovery-storage",
        syncState: "synchronized",
        rack: "VAULT-1",
      },
    ],
    connections: [
      {
        id: "hq-user-hq-gateway",
        from: "hq-user",
        to: "hq-gateway",
        kind: "service-link",
        strength: "strong",
        distanceKm: 1,
        latencyMs: 1,
        jitterMs: 0,
        packetLossPct: 0,
        throughputMBps: 9200,
        utilizationPct: 28,
        carrier: "Campus LAN",
        costUsd: 120,
        priority: 1,
        health: "healthy",
        recoveryAction: "serve-primary",
        policyId: "protect-primary",
        notes: "Enterprise access link is healthy.",
      },
      {
        id: "hq-gateway-primary-erp",
        from: "hq-gateway",
        to: "primary-erp",
        kind: "service-link",
        strength: "strong",
        distanceKm: 14,
        latencyMs: 5,
        jitterMs: 1,
        packetLossPct: 0.1,
        throughputMBps: 7600,
        utilizationPct: 44,
        carrier: "Primary MPLS",
        costUsd: 460,
        priority: 1,
        health: "healthy",
        recoveryAction: "serve-primary",
        policyId: "protect-primary",
        notes: "Primary application path is healthy.",
      },
      {
        id: "hq-gateway-recovery-erp",
        from: "hq-gateway",
        to: "recovery-erp",
        kind: "recovery-link",
        strength: "medium",
        distanceKm: 34,
        latencyMs: 11,
        jitterMs: 2,
        packetLossPct: 0.2,
        throughputMBps: 6800,
        utilizationPct: 36,
        carrier: "Recovery WAN",
        costUsd: 620,
        priority: 2,
        health: "healthy",
        recoveryAction: "standby-route",
        policyId: "protect-primary",
        notes: "Recovery path is warm and ready.",
      },
      {
        id: "primary-erp-recovery-erp",
        from: "primary-erp",
        to: "recovery-erp",
        kind: "replication-link",
        strength: "strong",
        distanceKm: 26,
        latencyMs: 8,
        jitterMs: 2,
        packetLossPct: 0.1,
        throughputMBps: 7200,
        utilizationPct: 48,
        carrier: "Replica Fabric",
        costUsd: 510,
        priority: 1,
        health: "healthy",
        recoveryAction: "sync-replica",
        policyId: "protect-primary",
        notes: "Replication is current and within RPO target.",
      },
      {
        id: "replication-controller-primary-erp",
        from: "replication-controller",
        to: "primary-erp",
        kind: "management-link",
        strength: "strong",
        distanceKm: 5,
        latencyMs: 2,
        jitterMs: 1,
        packetLossPct: 0,
        throughputMBps: 1600,
        utilizationPct: 12,
        carrier: "Control Plane",
        costUsd: 90,
        priority: 1,
        health: "healthy",
        recoveryAction: "monitor-primary",
        policyId: "protect-primary",
        notes: "Controller supervises primary continuity state.",
      },
      {
        id: "replication-controller-recovery-erp",
        from: "replication-controller",
        to: "recovery-erp",
        kind: "management-link",
        strength: "strong",
        distanceKm: 6,
        latencyMs: 2,
        jitterMs: 1,
        packetLossPct: 0,
        throughputMBps: 1600,
        utilizationPct: 13,
        carrier: "Control Plane",
        costUsd: 90,
        priority: 1,
        health: "healthy",
        recoveryAction: "monitor-recovery",
        policyId: "protect-primary",
        notes: "Controller tracks recovery readiness.",
      },
      {
        id: "recovery-erp-vault-storage",
        from: "recovery-erp",
        to: "vault-storage",
        kind: "replication-link",
        strength: "strong",
        distanceKm: 4,
        latencyMs: 2,
        jitterMs: 1,
        packetLossPct: 0,
        throughputMBps: 6400,
        utilizationPct: 34,
        carrier: "Vault Fabric",
        costUsd: 210,
        priority: 2,
        health: "healthy",
        recoveryAction: "archive-state",
        policyId: "protect-primary",
        notes: "Recovery vault retains synchronized snapshots.",
      },
    ],
  },
  {
    id: "active-active-failover",
    name: "Active Active Failover",
    summary:
      "The primary enterprise application is unavailable, so the continuity strategy promotes the recovery application and exposes replica lag as part of the failover posture.",
    defaultPolicyId: "promote-recovery",
    policies: [
      {
        id: "protect-primary",
        label: "Protect primary",
        summary:
          "Keep the primary application preferred when the primary site remains healthy enough to serve.",
        strategy: "active-passive",
        priority: 2,
      },
      {
        id: "promote-recovery",
        label: "Promote recovery",
        summary:
          "Serve the application through the recovery site when the primary site is unavailable or at excessive risk.",
        strategy: "active-active",
        priority: 1,
      },
    ],
    devices: [
      {
        id: "hq-user",
        label: "HQ User",
        kind: "enterprise-client",
        status: "online",
        x: 120,
        y: 280,
        detail:
          "Enterprise user requiring uninterrupted access to the business application during primary-site failure.",
        site: "HQ Campus",
        region: "Primary Campus",
        tier: "branch",
        role: "source",
        domain: "enterprise-edge",
        rack: "HQ-1",
      },
      {
        id: "hq-gateway",
        label: "HQ Gateway",
        kind: "branch-gateway",
        status: "online",
        x: 300,
        y: 280,
        detail: "Transport gateway that can pivot users onto the promoted recovery path.",
        site: "HQ Campus",
        region: "Primary Campus",
        tier: "transport",
        role: "gateway",
        domain: "transport",
        rack: "GW-1",
      },
      {
        id: "primary-erp",
        label: "Primary ERP",
        kind: "primary-app",
        status: "offline",
        x: 520,
        y: 200,
        detail: "Primary enterprise application lost with the failed primary site.",
        site: "Primary DC",
        region: "East Region",
        tier: "application",
        role: "primary",
        domain: "business-app",
        syncState: "lagging",
        rack: "APP-1",
        cluster: "erp-primary",
      },
      {
        id: "recovery-erp",
        label: "Recovery ERP",
        kind: "recovery-app",
        status: "online",
        x: 760,
        y: 320,
        detail: "Recovery application now serving production continuity traffic.",
        site: "Recovery DC",
        region: "West Region",
        tier: "application",
        role: "recovery",
        domain: "business-app",
        syncState: "recovering",
        rack: "APP-2",
        cluster: "erp-recovery",
      },
      {
        id: "replication-controller",
        label: "Replication Controller",
        kind: "replication-controller",
        status: "online",
        x: 520,
        y: 60,
        detail: "Continuity controller that has promoted the recovery application.",
        site: "Operations Core",
        region: "Control Plane",
        tier: "control",
        role: "controller",
        domain: "continuity-control",
        rack: "CTRL-1",
      },
      {
        id: "vault-storage",
        label: "Vault Storage",
        kind: "data-vault",
        status: "degraded",
        x: 760,
        y: 120,
        detail:
          "Recovery storage remains available, but snapshot freshness is behind the ideal RPO target.",
        site: "Recovery DC",
        region: "West Region",
        tier: "storage",
        role: "storage",
        domain: "recovery-storage",
        syncState: "lagging",
        rack: "VAULT-1",
      },
    ],
    connections: [
      {
        id: "hq-user-hq-gateway",
        from: "hq-user",
        to: "hq-gateway",
        kind: "service-link",
        strength: "strong",
        distanceKm: 1,
        latencyMs: 1,
        jitterMs: 0,
        packetLossPct: 0,
        throughputMBps: 9200,
        utilizationPct: 31,
        carrier: "Campus LAN",
        costUsd: 120,
        priority: 1,
        health: "healthy",
        recoveryAction: "serve-recovery",
        policyId: "promote-recovery",
        notes: "Enterprise access remains available.",
      },
      {
        id: "hq-gateway-primary-erp",
        from: "hq-gateway",
        to: "primary-erp",
        kind: "service-link",
        strength: "weak",
        distanceKm: 14,
        latencyMs: 0,
        jitterMs: 0,
        packetLossPct: 100,
        throughputMBps: 0,
        utilizationPct: 0,
        carrier: "Primary MPLS",
        costUsd: 460,
        priority: 1,
        health: "failed",
        recoveryAction: "primary-down",
        policyId: "promote-recovery",
        notes: "Primary site service path is unavailable.",
      },
      {
        id: "hq-gateway-recovery-erp",
        from: "hq-gateway",
        to: "recovery-erp",
        kind: "recovery-link",
        strength: "strong",
        distanceKm: 34,
        latencyMs: 10,
        jitterMs: 2,
        packetLossPct: 0.2,
        throughputMBps: 6500,
        utilizationPct: 51,
        carrier: "Recovery WAN",
        costUsd: 620,
        priority: 1,
        health: "healthy",
        recoveryAction: "promote-site",
        policyId: "promote-recovery",
        notes: "Recovery path has become the active production route.",
      },
      {
        id: "primary-erp-recovery-erp",
        from: "primary-erp",
        to: "recovery-erp",
        kind: "replication-link",
        strength: "medium",
        distanceKm: 26,
        latencyMs: 9,
        jitterMs: 3,
        packetLossPct: 0.4,
        throughputMBps: 4300,
        utilizationPct: 72,
        carrier: "Replica Fabric",
        costUsd: 510,
        priority: 2,
        health: "degraded",
        recoveryAction: "replay-log",
        policyId: "promote-recovery",
        notes: "Replication lag creates an elevated RPO risk.",
      },
      {
        id: "replication-controller-primary-erp",
        from: "replication-controller",
        to: "primary-erp",
        kind: "management-link",
        strength: "strong",
        distanceKm: 5,
        latencyMs: 2,
        jitterMs: 1,
        packetLossPct: 0,
        throughputMBps: 1600,
        utilizationPct: 12,
        carrier: "Control Plane",
        costUsd: 90,
        priority: 1,
        health: "healthy",
        recoveryAction: "declare-site-loss",
        policyId: "promote-recovery",
        notes: "Controller registered the primary-site outage.",
      },
      {
        id: "replication-controller-recovery-erp",
        from: "replication-controller",
        to: "recovery-erp",
        kind: "management-link",
        strength: "strong",
        distanceKm: 6,
        latencyMs: 2,
        jitterMs: 1,
        packetLossPct: 0,
        throughputMBps: 1600,
        utilizationPct: 14,
        carrier: "Control Plane",
        costUsd: 90,
        priority: 1,
        health: "healthy",
        recoveryAction: "promote-workload",
        policyId: "promote-recovery",
        notes: "Controller promoted the recovery application.",
      },
      {
        id: "recovery-erp-vault-storage",
        from: "recovery-erp",
        to: "vault-storage",
        kind: "replication-link",
        strength: "medium",
        distanceKm: 4,
        latencyMs: 3,
        jitterMs: 1,
        packetLossPct: 0.1,
        throughputMBps: 4100,
        utilizationPct: 59,
        carrier: "Vault Fabric",
        costUsd: 210,
        priority: 2,
        health: "degraded",
        recoveryAction: "protect-recovery",
        policyId: "promote-recovery",
        notes: "Vault snapshots are behind the ideal target but still usable.",
      },
    ],
  },
]
