import { RoutingSwitchingTopology } from "./routing-switching.models"

export const ROUTING_SWITCHING_TOPOLOGIES: RoutingSwitchingTopology[] = [
  {
    id: "branch-to-core",
    name: "Branch to Core",
    summary:
      "A branch office crosses a routed WAN handoff to reach shared services in the core network.",
    devices: [
      {
        id: "branch-client",
        label: "Branch PC",
        kind: "workstation",
        status: "online",
        x: 120,
        y: 350,
        detail: "Local branch endpoint that needs access to corporate services.",
        segment: "Branch LAN",
        role: "endpoint",
      },
      {
        id: "branch-switch",
        label: "Branch Switch",
        kind: "switch",
        status: "online",
        x: 265,
        y: 260,
        detail: "Aggregates branch access devices before the router handoff.",
        segment: "Branch LAN",
        role: "access",
      },
      {
        id: "branch-router",
        label: "Branch Router",
        kind: "router",
        status: "online",
        x: 420,
        y: 190,
        detail: "Routes branch traffic toward the core over the WAN link.",
        segment: "Branch WAN Edge",
        role: "distribution",
      },
      {
        id: "core-router",
        label: "Core Router",
        kind: "router",
        status: "online",
        x: 585,
        y: 190,
        detail: "Terminates the WAN handoff and forwards traffic into the core services segment.",
        segment: "Core Edge",
        role: "distribution",
      },
      {
        id: "core-switch",
        label: "Core Switch",
        kind: "core-switch",
        status: "online",
        x: 735,
        y: 260,
        detail: "Aggregates routed paths and distributes access to shared services.",
        segment: "Core Services",
        role: "core",
      },
      {
        id: "hq-server",
        label: "HQ Server",
        kind: "server",
        status: "online",
        x: 800,
        y: 390,
        detail: "Central service target for users arriving from the branch network.",
        segment: "Core Services",
        role: "endpoint",
      },
    ],
    connections: [
      {
        id: "branch-client-branch-switch",
        from: "branch-client",
        to: "branch-switch",
        kind: "ethernet",
        strength: "strong",
        metric: 1,
      },
      {
        id: "branch-switch-branch-router",
        from: "branch-switch",
        to: "branch-router",
        kind: "trunk",
        strength: "strong",
        metric: 1,
      },
      {
        id: "branch-router-core-router",
        from: "branch-router",
        to: "core-router",
        kind: "wan-link",
        strength: "medium",
        metric: 3,
      },
      {
        id: "core-router-core-switch",
        from: "core-router",
        to: "core-switch",
        kind: "routed-link",
        strength: "strong",
        metric: 1,
      },
      {
        id: "core-switch-hq-server",
        from: "core-switch",
        to: "hq-server",
        kind: "ethernet",
        strength: "strong",
        metric: 1,
      },
    ],
  },
  {
    id: "multi-subnet-campus",
    name: "Multi-Subnet Campus",
    summary:
      "Campus users cross access, distribution, and core layers to reach services in another subnet.",
    devices: [
      {
        id: "student-client",
        label: "Student PC",
        kind: "workstation",
        status: "online",
        x: 110,
        y: 390,
        detail: "Client in the student subnet that needs to reach a faculty service.",
        segment: "Student VLAN",
        role: "endpoint",
      },
      {
        id: "student-switch",
        label: "Student Access",
        kind: "switch",
        status: "online",
        x: 245,
        y: 275,
        detail: "Access switch for the student subnet and edge ports.",
        segment: "Student VLAN",
        role: "access",
      },
      {
        id: "distribution-router",
        label: "Distribution Router",
        kind: "router",
        status: "online",
        x: 415,
        y: 195,
        detail: "Moves traffic from the student access layer into the campus core.",
        segment: "Campus Distribution",
        role: "distribution",
      },
      {
        id: "campus-core",
        label: "Campus Core",
        kind: "core-switch",
        status: "online",
        x: 575,
        y: 180,
        detail: "High-capacity core switching domain connecting multiple routed segments.",
        segment: "Campus Core",
        role: "core",
      },
      {
        id: "faculty-router",
        label: "Faculty Router",
        kind: "router",
        status: "online",
        x: 710,
        y: 235,
        detail: "Routes traffic from the core toward the faculty service subnet.",
        segment: "Faculty Distribution",
        role: "distribution",
      },
      {
        id: "faculty-switch",
        label: "Faculty Access",
        kind: "switch",
        status: "online",
        x: 810,
        y: 335,
        detail: "Access layer switch for faculty endpoints and local services.",
        segment: "Faculty VLAN",
        role: "access",
      },
      {
        id: "faculty-server",
        label: "Faculty Server",
        kind: "server",
        status: "degraded",
        x: 895,
        y: 430,
        detail:
          "Destination service with mild degradation but still reachable through the campus core.",
        segment: "Faculty VLAN",
        role: "endpoint",
      },
    ],
    connections: [
      {
        id: "student-client-student-switch",
        from: "student-client",
        to: "student-switch",
        kind: "ethernet",
        strength: "strong",
        metric: 1,
      },
      {
        id: "student-switch-distribution-router",
        from: "student-switch",
        to: "distribution-router",
        kind: "trunk",
        strength: "strong",
        metric: 1,
      },
      {
        id: "distribution-router-campus-core",
        from: "distribution-router",
        to: "campus-core",
        kind: "routed-link",
        strength: "strong",
        metric: 1,
      },
      {
        id: "campus-core-faculty-router",
        from: "campus-core",
        to: "faculty-router",
        kind: "routed-link",
        strength: "medium",
        metric: 2,
      },
      {
        id: "faculty-router-faculty-switch",
        from: "faculty-router",
        to: "faculty-switch",
        kind: "trunk",
        strength: "strong",
        metric: 1,
      },
      {
        id: "faculty-switch-faculty-server",
        from: "faculty-switch",
        to: "faculty-server",
        kind: "ethernet",
        strength: "medium",
        metric: 1,
      },
    ],
  },
]
