import { LanTopology } from "./lan.models"

export const LAN_TOPOLOGIES: LanTopology[] = [
  {
    id: "branch-office",
    name: "Branch Office",
    summary:
      "A compact office LAN with shared switching, wireless access, and a small routed uplink.",
    devices: [
      {
        id: "branch-router",
        label: "Edge Router",
        kind: "router",
        status: "online",
        x: 420,
        y: 90,
        detail: "Provides WAN handoff and default gateway services for the branch.",
      },
      {
        id: "branch-switch",
        label: "Access Switch",
        kind: "switch",
        status: "online",
        x: 420,
        y: 220,
        detail: "Aggregates wired endpoints and uplinks to the router.",
      },
      {
        id: "branch-ap",
        label: "Lobby AP",
        kind: "access-point",
        status: "online",
        x: 650,
        y: 190,
        detail: "Provides local wireless coverage for roaming clients.",
      },
      {
        id: "branch-workstation-a",
        label: "Finance PC",
        kind: "workstation",
        status: "online",
        x: 210,
        y: 350,
        detail: "Wired workstation attached to the main access layer.",
      },
      {
        id: "branch-workstation-b",
        label: "Reception PC",
        kind: "workstation",
        status: "degraded",
        x: 430,
        y: 390,
        detail: "Experiencing intermittent local connectivity on the floor switch.",
      },
      {
        id: "branch-printer",
        label: "Shared Printer",
        kind: "printer",
        status: "online",
        x: 640,
        y: 350,
        detail: "Common print endpoint published to staff devices.",
      },
    ],
    connections: [
      {
        id: "branch-router-switch",
        from: "branch-router",
        to: "branch-switch",
        kind: "uplink",
        strength: "strong",
      },
      {
        id: "branch-switch-ap",
        from: "branch-switch",
        to: "branch-ap",
        kind: "ethernet",
        strength: "strong",
      },
      {
        id: "branch-switch-workstation-a",
        from: "branch-switch",
        to: "branch-workstation-a",
        kind: "ethernet",
        strength: "strong",
      },
      {
        id: "branch-switch-workstation-b",
        from: "branch-switch",
        to: "branch-workstation-b",
        kind: "ethernet",
        strength: "medium",
      },
      {
        id: "branch-switch-printer",
        from: "branch-switch",
        to: "branch-printer",
        kind: "ethernet",
        strength: "strong",
      },
    ],
  },
  {
    id: "server-room",
    name: "Server Room",
    summary:
      "A small server room with a routed edge, core switching, and east-west traffic between services.",
    devices: [
      {
        id: "server-router",
        label: "Core Router",
        kind: "router",
        status: "online",
        x: 430,
        y: 80,
        detail: "Upstream handoff into the local data and management segments.",
      },
      {
        id: "server-core-switch",
        label: "Core Switch",
        kind: "switch",
        status: "online",
        x: 430,
        y: 205,
        detail: "Central aggregation point for the room and trunk termination.",
      },
      {
        id: "server-access-switch",
        label: "Rack Switch",
        kind: "switch",
        status: "online",
        x: 220,
        y: 315,
        detail: "Distributes access links to nearby infrastructure nodes.",
      },
      {
        id: "server-app",
        label: "App Server",
        kind: "server",
        status: "online",
        x: 430,
        y: 360,
        detail: "Hosts internal services used by staff and line-of-business apps.",
      },
      {
        id: "server-storage",
        label: "Storage Server",
        kind: "server",
        status: "degraded",
        x: 640,
        y: 315,
        detail: "Running but under stress, with elevated I/O and reduced headroom.",
      },
      {
        id: "server-ops",
        label: "Ops Console",
        kind: "workstation",
        status: "online",
        x: 640,
        y: 430,
        detail: "Administrator workstation used for monitoring and intervention.",
      },
    ],
    connections: [
      {
        id: "server-router-core",
        from: "server-router",
        to: "server-core-switch",
        kind: "uplink",
        strength: "strong",
      },
      {
        id: "server-core-access",
        from: "server-core-switch",
        to: "server-access-switch",
        kind: "trunk",
        strength: "strong",
      },
      {
        id: "server-core-app",
        from: "server-core-switch",
        to: "server-app",
        kind: "ethernet",
        strength: "strong",
      },
      {
        id: "server-core-storage",
        from: "server-core-switch",
        to: "server-storage",
        kind: "ethernet",
        strength: "medium",
      },
      {
        id: "server-access-ops",
        from: "server-access-switch",
        to: "server-ops",
        kind: "ethernet",
        strength: "strong",
      },
    ],
  },
  {
    id: "office-floor",
    name: "Office Floor",
    summary:
      "An open office floor balancing wired desks with wireless coverage for flexible seating.",
    devices: [
      {
        id: "floor-switch",
        label: "Floor Switch",
        kind: "switch",
        status: "online",
        x: 420,
        y: 190,
        detail: "Primary access switch serving desks and shared peripherals.",
      },
      {
        id: "floor-ap-west",
        label: "West AP",
        kind: "access-point",
        status: "online",
        x: 190,
        y: 150,
        detail: "Wireless coverage for collaboration and hot-desk areas.",
      },
      {
        id: "floor-ap-east",
        label: "East AP",
        kind: "access-point",
        status: "online",
        x: 650,
        y: 150,
        detail: "Secondary AP handling client density on the east wing.",
      },
      {
        id: "floor-design",
        label: "Design Workstation",
        kind: "workstation",
        status: "online",
        x: 245,
        y: 365,
        detail: "High-performance desk for design and content workflows.",
      },
      {
        id: "floor-sales",
        label: "Sales Workstation",
        kind: "workstation",
        status: "online",
        x: 430,
        y: 410,
        detail: "Client-facing workstation used for CRM and VoIP applications.",
      },
      {
        id: "floor-printer",
        label: "Floor Printer",
        kind: "printer",
        status: "offline",
        x: 640,
        y: 360,
        detail: "Shared device currently unavailable to the local floor users.",
      },
    ],
    connections: [
      {
        id: "floor-switch-ap-west",
        from: "floor-switch",
        to: "floor-ap-west",
        kind: "ethernet",
        strength: "strong",
      },
      {
        id: "floor-switch-ap-east",
        from: "floor-switch",
        to: "floor-ap-east",
        kind: "ethernet",
        strength: "strong",
      },
      {
        id: "floor-switch-design",
        from: "floor-switch",
        to: "floor-design",
        kind: "ethernet",
        strength: "strong",
      },
      {
        id: "floor-switch-sales",
        from: "floor-switch",
        to: "floor-sales",
        kind: "ethernet",
        strength: "strong",
      },
      {
        id: "floor-ap-east-printer",
        from: "floor-ap-east",
        to: "floor-printer",
        kind: "wireless",
        strength: "weak",
      },
    ],
  },
]
