import { CenTopology } from "./cen.models"

export const CEN_TOPOLOGIES: CenTopology[] = [
  {
    id: "nearest-region-preference",
    name: "Nearest Region Preference",
    summary:
      "An edge workload reaches a cloud service through the nearest on-ramp and region while a longer secondary path remains ready for cloud failover.",
    policies: [
      {
        id: "prefer-nearest-region",
        label: "Prefer nearest region",
        summary:
          "Keep traffic on the lowest-latency cloud on-ramp and shift to the alternate region only when the preferred path degrades or fails.",
      },
    ],
    devices: [
      {
        id: "storefront-edge",
        label: "Storefront Edge",
        kind: "edge-workload",
        status: "online",
        x: 120,
        y: 220,
        detail:
          "Retail edge application that synchronizes customer requests with the nearest cloud region.",
        site: "Branch 14",
        region: "Storefront Floor",
        tier: "edge",
        role: "edge",
        rack: "E-14",
        cluster: "retail",
        zone: "local-cache",
      },
      {
        id: "telemetry-edge",
        label: "Telemetry Edge",
        kind: "edge-workload",
        status: "online",
        x: 120,
        y: 400,
        detail:
          "Secondary edge process that continues sending site telemetry if the primary workload goes offline.",
        site: "Branch 14",
        region: "Storefront Floor",
        tier: "edge",
        role: "edge",
        rack: "E-16",
        cluster: "telemetry",
        zone: "sensor-bus",
      },
      {
        id: "branch-gateway",
        label: "Branch Gateway",
        kind: "edge-gateway",
        status: "online",
        x: 290,
        y: 300,
        detail:
          "Local edge gateway that aggregates site workloads before steering traffic into the cloud on-ramp layer.",
        site: "Branch 14",
        region: "Edge Gateway Layer",
        tier: "gateway",
        role: "gateway",
        rack: "GW-14",
        zone: "local-breakout",
      },
      {
        id: "onramp-east",
        label: "On-ramp East",
        kind: "cloud-onramp",
        status: "online",
        x: 500,
        y: 170,
        detail: "Primary managed on-ramp into the nearest cloud fabric.",
        site: "Metro East",
        region: "Cloud On-ramp Layer",
        tier: "gateway",
        role: "gateway",
        rack: "OR-E1",
        zone: "managed-edge",
      },
      {
        id: "onramp-west",
        label: "On-ramp West",
        kind: "cloud-onramp",
        status: "online",
        x: 500,
        y: 430,
        detail: "Secondary internet-based on-ramp kept ready for regional failover.",
        site: "Metro West",
        region: "Cloud On-ramp Layer",
        tier: "gateway",
        role: "gateway",
        rack: "OR-W1",
        zone: "internet-edge",
      },
      {
        id: "cloud-east",
        label: "Cloud East",
        kind: "cloud-region",
        status: "online",
        x: 700,
        y: 170,
        detail: "Nearest cloud region that hosts the preferred service replica for the branch.",
        site: "Region East",
        region: "Cloud Region Tier",
        tier: "cloud",
        role: "cloud",
        rack: "REG-E",
        zone: "east-1",
      },
      {
        id: "cloud-west",
        label: "Cloud West",
        kind: "cloud-region",
        status: "online",
        x: 700,
        y: 430,
        detail:
          "Secondary cloud region that protects the application path during regional degradation.",
        site: "Region West",
        region: "Cloud Region Tier",
        tier: "cloud",
        role: "cloud",
        rack: "REG-W",
        zone: "west-2",
      },
      {
        id: "orders-api",
        label: "Orders API",
        kind: "service-endpoint",
        status: "online",
        x: 920,
        y: 220,
        detail:
          "Cloud-hosted transactional API exposed from both regions so the edge can fail over without changing the destination service.",
        site: "Global Service Mesh",
        region: "Application Layer",
        tier: "service",
        role: "service",
        rack: "APP-ORD",
        cluster: "orders",
        zone: "multi-region",
      },
      {
        id: "analytics-api",
        label: "Analytics API",
        kind: "service-endpoint",
        status: "online",
        x: 920,
        y: 400,
        detail:
          "Secondary cloud analytics endpoint that shares the same cloud path options while targeting a different application service.",
        site: "Global Service Mesh",
        region: "Application Layer",
        tier: "service",
        role: "service",
        rack: "APP-ANA",
        cluster: "analytics",
        zone: "multi-region",
      },
    ],
    connections: [
      {
        id: "storefront-edge-branch-gateway",
        from: "storefront-edge",
        to: "branch-gateway",
        kind: "local-link",
        strength: "strong",
        distanceKm: 1,
        latencyMs: 1,
        jitterMs: 0,
        packetLossPct: 0,
        throughputMBps: 10000,
        iops: 0,
        utilizationPct: 45,
        carrier: "Storefront LAN",
        costUsd: 150,
        priority: 1,
      },
      {
        id: "telemetry-edge-branch-gateway",
        from: "telemetry-edge",
        to: "branch-gateway",
        kind: "local-link",
        strength: "strong",
        distanceKm: 1,
        latencyMs: 1,
        jitterMs: 0,
        packetLossPct: 0,
        throughputMBps: 8000,
        iops: 0,
        utilizationPct: 38,
        carrier: "Sensor LAN",
        costUsd: 150,
        priority: 1,
      },
      {
        id: "branch-gateway-onramp-east",
        from: "branch-gateway",
        to: "onramp-east",
        kind: "edge-uplink",
        strength: "strong",
        distanceKm: 12,
        latencyMs: 4,
        jitterMs: 1,
        packetLossPct: 0.1,
        throughputMBps: 9000,
        iops: 0,
        utilizationPct: 52,
        carrier: "Metro Edge",
        costUsd: 1400,
        priority: 1,
      },
      {
        id: "branch-gateway-onramp-west",
        from: "branch-gateway",
        to: "onramp-west",
        kind: "edge-uplink",
        strength: "strong",
        distanceKm: 18,
        latencyMs: 7,
        jitterMs: 2,
        packetLossPct: 0.1,
        throughputMBps: 7000,
        iops: 0,
        utilizationPct: 36,
        carrier: "Internet Edge",
        costUsd: 900,
        priority: 2,
      },
      {
        id: "onramp-east-cloud-east",
        from: "onramp-east",
        to: "cloud-east",
        kind: "cloud-backbone",
        strength: "strong",
        distanceKm: 40,
        latencyMs: 6,
        jitterMs: 2,
        packetLossPct: 0,
        throughputMBps: 8500,
        iops: 0,
        utilizationPct: 48,
        carrier: "Cloud Backbone East",
        costUsd: 1100,
        priority: 1,
      },
      {
        id: "onramp-west-cloud-west",
        from: "onramp-west",
        to: "cloud-west",
        kind: "cloud-backbone",
        strength: "strong",
        distanceKm: 65,
        latencyMs: 11,
        jitterMs: 3,
        packetLossPct: 0,
        throughputMBps: 6500,
        iops: 0,
        utilizationPct: 33,
        carrier: "Cloud Backbone West",
        costUsd: 900,
        priority: 2,
      },
      {
        id: "cloud-east-orders-api",
        from: "cloud-east",
        to: "orders-api",
        kind: "service-link",
        strength: "strong",
        distanceKm: 3,
        latencyMs: 2,
        jitterMs: 0,
        packetLossPct: 0,
        throughputMBps: 10000,
        iops: 0,
        utilizationPct: 44,
        carrier: "Region East Mesh",
        costUsd: 300,
        priority: 1,
      },
      {
        id: "cloud-west-orders-api",
        from: "cloud-west",
        to: "orders-api",
        kind: "service-link",
        strength: "strong",
        distanceKm: 5,
        latencyMs: 4,
        jitterMs: 1,
        packetLossPct: 0,
        throughputMBps: 7000,
        iops: 0,
        utilizationPct: 29,
        carrier: "Region West Mesh",
        costUsd: 280,
        priority: 2,
      },
      {
        id: "cloud-east-analytics-api",
        from: "cloud-east",
        to: "analytics-api",
        kind: "service-link",
        strength: "strong",
        distanceKm: 3,
        latencyMs: 2,
        jitterMs: 0,
        packetLossPct: 0,
        throughputMBps: 9600,
        iops: 0,
        utilizationPct: 41,
        carrier: "Region East Mesh",
        costUsd: 320,
        priority: 1,
      },
      {
        id: "cloud-west-analytics-api",
        from: "cloud-west",
        to: "analytics-api",
        kind: "service-link",
        strength: "strong",
        distanceKm: 5,
        latencyMs: 4,
        jitterMs: 0,
        packetLossPct: 0,
        throughputMBps: 6800,
        iops: 0,
        utilizationPct: 27,
        carrier: "Region West Mesh",
        costUsd: 280,
        priority: 2,
      },
    ],
  },
  {
    id: "regional-failover",
    name: "Regional Failover",
    summary:
      "The preferred cloud route stays active while the primary on-ramp is degraded, and traffic fails over to the recovery region when the primary edge becomes unavailable.",
    policies: [
      {
        id: "preserve-service-continuity",
        label: "Preserve service continuity",
        summary:
          "Keep the primary route until it fails, then steer the edge workload into the recovery region with the fewest surviving hops.",
      },
    ],
    devices: [
      {
        id: "kiosk-edge",
        label: "Kiosk Edge",
        kind: "edge-workload",
        status: "online",
        x: 120,
        y: 220,
        detail:
          "Primary branch application that keeps local sessions alive while relying on a cloud service for state sync.",
        site: "Retail Pod 8",
        region: "Checkout Row",
        tier: "edge",
        role: "edge",
        rack: "K-08",
        cluster: "checkout",
        zone: "session-cache",
      },
      {
        id: "sensor-edge",
        label: "Sensor Edge",
        kind: "edge-workload",
        status: "online",
        x: 120,
        y: 400,
        detail:
          "Secondary edge process that can continue feeding events into the cloud if the kiosk edge goes offline.",
        site: "Retail Pod 8",
        region: "Checkout Row",
        tier: "edge",
        role: "edge",
        rack: "S-08",
        cluster: "sensors",
        zone: "event-cache",
      },
      {
        id: "retail-gateway",
        label: "Retail Gateway",
        kind: "edge-gateway",
        status: "online",
        x: 290,
        y: 300,
        detail:
          "Regional edge gateway that brokers failover from the branch into primary or recovery cloud paths.",
        site: "Retail Pod 8",
        region: "Edge Gateway Layer",
        tier: "gateway",
        role: "gateway",
        rack: "GW-08",
        zone: "regional-breakout",
      },
      {
        id: "onramp-primary",
        label: "On-ramp Primary",
        kind: "cloud-onramp",
        status: "degraded",
        x: 500,
        y: 170,
        detail:
          "Primary cloud on-ramp experiencing packet variation but still preferred while it remains available.",
        site: "Metro Primary",
        region: "Cloud On-ramp Layer",
        tier: "gateway",
        role: "gateway",
        rack: "OR-P",
        zone: "managed-edge",
      },
      {
        id: "onramp-secondary",
        label: "On-ramp Secondary",
        kind: "cloud-onramp",
        status: "online",
        x: 500,
        y: 430,
        detail: "Secondary cloud on-ramp used when the primary entry point is no longer reachable.",
        site: "Metro Secondary",
        region: "Cloud On-ramp Layer",
        tier: "gateway",
        role: "gateway",
        rack: "OR-S",
        zone: "internet-edge",
      },
      {
        id: "cloud-central",
        label: "Cloud Central",
        kind: "cloud-region",
        status: "online",
        x: 700,
        y: 170,
        detail: "Primary cloud region for the application service.",
        site: "Central Region",
        region: "Cloud Region Tier",
        tier: "cloud",
        role: "cloud",
        rack: "REG-C",
        zone: "central-1",
      },
      {
        id: "cloud-recovery",
        label: "Cloud Recovery",
        kind: "cloud-region",
        status: "online",
        x: 700,
        y: 430,
        detail:
          "Recovery cloud region that keeps services reachable if the preferred region path fails.",
        site: "Recovery Region",
        region: "Cloud Region Tier",
        tier: "cloud",
        role: "cloud",
        rack: "REG-R",
        zone: "recovery-1",
      },
      {
        id: "session-api",
        label: "Session API",
        kind: "service-endpoint",
        status: "online",
        x: 920,
        y: 220,
        detail:
          "Session service presented from both regions so the branch can fail over without changing application intent.",
        site: "Global Service Mesh",
        region: "Application Layer",
        tier: "service",
        role: "service",
        rack: "APP-SES",
        cluster: "session",
        zone: "multi-region",
      },
      {
        id: "event-bus",
        label: "Event Bus",
        kind: "service-endpoint",
        status: "online",
        x: 920,
        y: 400,
        detail:
          "Regional event intake that shares the same path choices as the primary session API.",
        site: "Global Service Mesh",
        region: "Application Layer",
        tier: "service",
        role: "service",
        rack: "APP-EVT",
        cluster: "events",
        zone: "multi-region",
      },
    ],
    connections: [
      {
        id: "kiosk-edge-retail-gateway",
        from: "kiosk-edge",
        to: "retail-gateway",
        kind: "local-link",
        strength: "strong",
        distanceKm: 1,
        latencyMs: 2,
        jitterMs: 0,
        packetLossPct: 0,
        throughputMBps: 8200,
        iops: 0,
        utilizationPct: 47,
        carrier: "Kiosk LAN",
        costUsd: 140,
        priority: 1,
      },
      {
        id: "sensor-edge-retail-gateway",
        from: "sensor-edge",
        to: "retail-gateway",
        kind: "local-link",
        strength: "strong",
        distanceKm: 1,
        latencyMs: 2,
        jitterMs: 0,
        packetLossPct: 0,
        throughputMBps: 7600,
        iops: 0,
        utilizationPct: 34,
        carrier: "Sensor LAN",
        costUsd: 140,
        priority: 1,
      },
      {
        id: "retail-gateway-onramp-primary",
        from: "retail-gateway",
        to: "onramp-primary",
        kind: "edge-uplink",
        strength: "medium",
        distanceKm: 14,
        latencyMs: 5,
        jitterMs: 3,
        packetLossPct: 0.3,
        throughputMBps: 7800,
        iops: 0,
        utilizationPct: 61,
        carrier: "Managed Edge",
        costUsd: 1500,
        priority: 1,
      },
      {
        id: "retail-gateway-onramp-secondary",
        from: "retail-gateway",
        to: "onramp-secondary",
        kind: "edge-uplink",
        strength: "strong",
        distanceKm: 22,
        latencyMs: 8,
        jitterMs: 2,
        packetLossPct: 0.1,
        throughputMBps: 6400,
        iops: 0,
        utilizationPct: 39,
        carrier: "Internet Backup",
        costUsd: 920,
        priority: 2,
      },
      {
        id: "onramp-primary-cloud-central",
        from: "onramp-primary",
        to: "cloud-central",
        kind: "cloud-backbone",
        strength: "medium",
        distanceKm: 48,
        latencyMs: 7,
        jitterMs: 3,
        packetLossPct: 0.2,
        throughputMBps: 7600,
        iops: 0,
        utilizationPct: 58,
        carrier: "Cloud Core Primary",
        costUsd: 1200,
        priority: 1,
      },
      {
        id: "onramp-secondary-cloud-recovery",
        from: "onramp-secondary",
        to: "cloud-recovery",
        kind: "cloud-backbone",
        strength: "strong",
        distanceKm: 74,
        latencyMs: 12,
        jitterMs: 4,
        packetLossPct: 0.1,
        throughputMBps: 6100,
        iops: 0,
        utilizationPct: 36,
        carrier: "Cloud Core Recovery",
        costUsd: 980,
        priority: 2,
      },
      {
        id: "cloud-central-session-api",
        from: "cloud-central",
        to: "session-api",
        kind: "service-link",
        strength: "strong",
        distanceKm: 3,
        latencyMs: 2,
        jitterMs: 1,
        packetLossPct: 0,
        throughputMBps: 9000,
        iops: 0,
        utilizationPct: 43,
        carrier: "Central Mesh",
        costUsd: 310,
        priority: 1,
      },
      {
        id: "cloud-recovery-session-api",
        from: "cloud-recovery",
        to: "session-api",
        kind: "service-link",
        strength: "strong",
        distanceKm: 6,
        latencyMs: 4,
        jitterMs: 1,
        packetLossPct: 0,
        throughputMBps: 6900,
        iops: 0,
        utilizationPct: 31,
        carrier: "Recovery Mesh",
        costUsd: 290,
        priority: 2,
      },
      {
        id: "cloud-central-event-bus",
        from: "cloud-central",
        to: "event-bus",
        kind: "service-link",
        strength: "strong",
        distanceKm: 3,
        latencyMs: 2,
        jitterMs: 1,
        packetLossPct: 0,
        throughputMBps: 8800,
        iops: 0,
        utilizationPct: 40,
        carrier: "Central Mesh",
        costUsd: 300,
        priority: 1,
      },
      {
        id: "cloud-recovery-event-bus",
        from: "cloud-recovery",
        to: "event-bus",
        kind: "service-link",
        strength: "strong",
        distanceKm: 6,
        latencyMs: 4,
        jitterMs: 1,
        packetLossPct: 0,
        throughputMBps: 6600,
        iops: 0,
        utilizationPct: 30,
        carrier: "Recovery Mesh",
        costUsd: 280,
        priority: 2,
      },
    ],
  },
]
