import { SanTopology } from "./san.models"

export const SAN_TOPOLOGIES: SanTopology[] = [
  {
    id: "primary-backup-storage",
    name: "Primary Backup Storage",
    summary:
      "An application host reaches a primary storage array over the preferred fabric and automatically fails over to a replicated backup target when the primary target becomes unavailable.",
    policies: [
      {
        id: "automatic-failover",
        label: "Automatic failover",
        summary:
          "Prefer the primary array and move to the protected path only when storage resiliency requires it.",
      },
    ],
    devices: [
      {
        id: "app-host",
        label: "App Host",
        kind: "client-node",
        status: "online",
        x: 120,
        y: 240,
        detail:
          "Primary application host that prefers the low-latency storage fabric path to the main array.",
        site: "Application Host",
        region: "Cluster A",
        tier: "host",
        role: "initiator",
      },
      {
        id: "batch-host",
        label: "Batch Host",
        kind: "client-node",
        status: "online",
        x: 120,
        y: 400,
        detail:
          "Secondary initiator that can take over storage access if the primary application host is unavailable.",
        site: "Batch Host",
        region: "Cluster B",
        tier: "host",
        role: "initiator",
      },
      {
        id: "storage-controller",
        label: "Storage Controller",
        kind: "storage-controller",
        status: "online",
        x: 460,
        y: 90,
        detail:
          "Array control-plane node that monitors replication health and orchestrates failover between the primary and backup storage targets.",
        site: "Control Pair",
        region: "Storage Core",
        tier: "control",
        role: "controller",
      },
      {
        id: "fabric-a",
        label: "Fabric A",
        kind: "fabric-switch",
        status: "online",
        x: 360,
        y: 220,
        detail:
          "Preferred fibre-channel fabric switch with the fastest path to the primary storage array.",
        site: "Primary Fabric",
        region: "Fabric Ring",
        tier: "fabric",
        role: "fabric",
      },
      {
        id: "fabric-b",
        label: "Fabric B",
        kind: "fabric-switch",
        status: "online",
        x: 360,
        y: 420,
        detail:
          "Backup storage fabric switch that carries traffic to the replicated storage target during failover.",
        site: "Backup Fabric",
        region: "Fabric Ring",
        tier: "fabric",
        role: "fabric",
      },
      {
        id: "primary-array",
        label: "Primary Array",
        kind: "storage-target",
        status: "online",
        x: 820,
        y: 210,
        detail:
          "Primary all-flash storage target serving production workloads on the preferred SAN path.",
        site: "Primary Array",
        region: "Row A",
        tier: "storage",
        role: "target",
        storagePool: "prod-a",
        replicationState: "synchronized",
      },
      {
        id: "backup-array",
        label: "Backup Array",
        kind: "backup-storage",
        status: "online",
        x: 820,
        y: 420,
        detail:
          "Replicated backup storage target that takes over production traffic when the primary array is unavailable.",
        site: "Backup Array",
        region: "Row B",
        tier: "storage",
        role: "target",
        storagePool: "prod-b",
        replicationState: "serving-replica",
      },
    ],
    connections: [
      {
        id: "app-host-fabric-a",
        from: "app-host",
        to: "fabric-a",
        kind: "fiber-channel",
        strength: "strong",
        distanceKm: 1,
        latencyMs: 2,
        jitterMs: 0,
        packetLossPct: 0,
        throughputMBps: 3200,
        iops: 220000,
        carrier: "Fabric A",
        costUsd: 1800,
        priority: 1,
      },
      {
        id: "fabric-a-primary-array",
        from: "fabric-a",
        to: "primary-array",
        kind: "fiber-channel",
        strength: "strong",
        distanceKm: 2,
        latencyMs: 3,
        jitterMs: 1,
        packetLossPct: 0,
        throughputMBps: 3200,
        iops: 220000,
        carrier: "Fabric A",
        costUsd: 2400,
        priority: 1,
      },
      {
        id: "app-host-fabric-b",
        from: "app-host",
        to: "fabric-b",
        kind: "backup-link",
        strength: "medium",
        distanceKm: 2,
        latencyMs: 6,
        jitterMs: 2,
        packetLossPct: 0.1,
        throughputMBps: 1800,
        iops: 120000,
        carrier: "Fabric B",
        costUsd: 1100,
        priority: 2,
      },
      {
        id: "fabric-b-backup-array",
        from: "fabric-b",
        to: "backup-array",
        kind: "backup-link",
        strength: "strong",
        distanceKm: 3,
        latencyMs: 7,
        jitterMs: 2,
        packetLossPct: 0.1,
        throughputMBps: 1800,
        iops: 120000,
        carrier: "Fabric B",
        costUsd: 1300,
        priority: 2,
      },
      {
        id: "batch-host-fabric-a",
        from: "batch-host",
        to: "fabric-a",
        kind: "sas-link",
        strength: "strong",
        distanceKm: 1,
        latencyMs: 4,
        jitterMs: 1,
        packetLossPct: 0,
        throughputMBps: 2400,
        iops: 160000,
        carrier: "Fabric A",
        costUsd: 1600,
        priority: 1,
      },
      {
        id: "batch-host-fabric-b",
        from: "batch-host",
        to: "fabric-b",
        kind: "backup-link",
        strength: "medium",
        distanceKm: 2,
        latencyMs: 7,
        jitterMs: 2,
        packetLossPct: 0.1,
        throughputMBps: 1400,
        iops: 90000,
        carrier: "Fabric B",
        costUsd: 900,
        priority: 2,
      },
      {
        id: "primary-array-backup-array",
        from: "primary-array",
        to: "backup-array",
        kind: "mgmt-link",
        strength: "strong",
        distanceKm: 1,
        latencyMs: 1,
        jitterMs: 0,
        packetLossPct: 0,
        throughputMBps: 900,
        iops: 0,
        carrier: "Replication Link",
        costUsd: 600,
        priority: 9,
      },
      {
        id: "storage-controller-primary-array",
        from: "storage-controller",
        to: "primary-array",
        kind: "mgmt-link",
        strength: "strong",
        distanceKm: 1,
        latencyMs: 1,
        jitterMs: 0,
        packetLossPct: 0,
        throughputMBps: 200,
        iops: 0,
        carrier: "Control LAN",
        costUsd: 300,
        priority: 9,
      },
      {
        id: "storage-controller-backup-array",
        from: "storage-controller",
        to: "backup-array",
        kind: "mgmt-link",
        strength: "strong",
        distanceKm: 1,
        latencyMs: 1,
        jitterMs: 0,
        packetLossPct: 0,
        throughputMBps: 200,
        iops: 0,
        carrier: "Control LAN",
        costUsd: 300,
        priority: 9,
      },
    ],
  },
  {
    id: "dual-fabric-storage",
    name: "Dual Fabric Storage",
    summary:
      "A host reaches the same storage target through two SAN fabrics, preferring the lower-latency primary fabric while retaining a protected backup path.",
    policies: [
      {
        id: "protected-primary",
        label: "Protected primary",
        summary:
          "Prefer the shorter fabric while keeping the protected path available for failover.",
      },
    ],
    devices: [
      {
        id: "analytics-host",
        label: "Analytics Host",
        kind: "client-node",
        status: "online",
        x: 125,
        y: 310,
        detail:
          "Latency-sensitive analytics initiator that prefers the shorter fabric path to the flash array.",
        site: "Analytics Host",
        region: "Cluster C",
        tier: "host",
        role: "initiator",
      },
      {
        id: "storage-controller-b",
        label: "Storage Controller B",
        kind: "storage-controller",
        status: "online",
        x: 455,
        y: 80,
        detail: "Controller pair for the dual-fabric array, tracking primary and protected paths.",
        site: "Control Pair B",
        region: "Storage Core",
        tier: "control",
        role: "controller",
      },
      {
        id: "fabric-east",
        label: "Fabric East",
        kind: "fabric-switch",
        status: "degraded",
        x: 380,
        y: 210,
        detail:
          "Primary SAN fabric with the shortest path to the flash array, but currently operating in a degraded state.",
        site: "Fabric East",
        region: "Fabric East",
        tier: "fabric",
        role: "fabric",
      },
      {
        id: "fabric-west",
        label: "Fabric West",
        kind: "fabric-switch",
        status: "online",
        x: 380,
        y: 420,
        detail: "Protected secondary fabric that carries the host if the primary fabric drops.",
        site: "Fabric West",
        region: "Fabric West",
        tier: "fabric",
        role: "fabric",
      },
      {
        id: "flash-array",
        label: "Flash Array",
        kind: "storage-target",
        status: "online",
        x: 820,
        y: 230,
        detail: "Primary flash storage target with dual-fabric connectivity.",
        site: "Flash Array",
        region: "Row C",
        tier: "storage",
        role: "target",
        storagePool: "analytics",
        replicationState: "synchronized",
      },
      {
        id: "vault-replica",
        label: "Vault Replica",
        kind: "backup-storage",
        status: "online",
        x: 820,
        y: 420,
        detail: "Replica target maintained over the management fabric for data protection.",
        site: "Vault Replica",
        region: "Row D",
        tier: "storage",
        role: "target",
        storagePool: "analytics-replica",
        replicationState: "serving-replica",
      },
    ],
    connections: [
      {
        id: "analytics-host-fabric-east",
        from: "analytics-host",
        to: "fabric-east",
        kind: "fiber-channel",
        strength: "medium",
        distanceKm: 1,
        latencyMs: 3,
        jitterMs: 1,
        packetLossPct: 0.1,
        throughputMBps: 2800,
        iops: 180000,
        carrier: "Fabric East",
        costUsd: 1700,
        priority: 1,
      },
      {
        id: "fabric-east-flash-array",
        from: "fabric-east",
        to: "flash-array",
        kind: "fiber-channel",
        strength: "medium",
        distanceKm: 2,
        latencyMs: 4,
        jitterMs: 1,
        packetLossPct: 0.1,
        throughputMBps: 2800,
        iops: 180000,
        carrier: "Fabric East",
        costUsd: 2000,
        priority: 1,
      },
      {
        id: "analytics-host-fabric-west",
        from: "analytics-host",
        to: "fabric-west",
        kind: "backup-link",
        strength: "strong",
        distanceKm: 2,
        latencyMs: 6,
        jitterMs: 2,
        packetLossPct: 0.1,
        throughputMBps: 2200,
        iops: 140000,
        carrier: "Fabric West",
        costUsd: 1100,
        priority: 2,
      },
      {
        id: "fabric-west-flash-array",
        from: "fabric-west",
        to: "flash-array",
        kind: "backup-link",
        strength: "strong",
        distanceKm: 3,
        latencyMs: 7,
        jitterMs: 2,
        packetLossPct: 0.1,
        throughputMBps: 2200,
        iops: 140000,
        carrier: "Fabric West",
        costUsd: 1200,
        priority: 2,
      },
      {
        id: "flash-array-vault-replica",
        from: "flash-array",
        to: "vault-replica",
        kind: "mgmt-link",
        strength: "strong",
        distanceKm: 1,
        latencyMs: 1,
        jitterMs: 0,
        packetLossPct: 0,
        throughputMBps: 1000,
        iops: 0,
        carrier: "Replication Link",
        costUsd: 500,
        priority: 9,
      },
      {
        id: "storage-controller-b-flash-array",
        from: "storage-controller-b",
        to: "flash-array",
        kind: "mgmt-link",
        strength: "strong",
        distanceKm: 1,
        latencyMs: 1,
        jitterMs: 0,
        packetLossPct: 0,
        throughputMBps: 200,
        iops: 0,
        carrier: "Control LAN",
        costUsd: 250,
        priority: 9,
      },
    ],
  },
]
