import { WlanTopology } from "./wlan.models"

export const WLAN_TOPOLOGIES: WlanTopology[] = [
  {
    id: "office-roaming",
    name: "Office Roaming",
    summary:
      "A mobile client can roam between overlapping office access points while maintaining uplink reachability.",
    devices: [
      {
        id: "ap-lobby",
        label: "Lobby AP",
        kind: "access-point",
        status: "online",
        x: 220,
        y: 170,
        detail: "Lobby access point serving the reception and meeting rooms.",
        zone: "Lobby",
        role: "access",
        band: "tri-band",
        channel: "5 GHz ch 44",
        coverageRadius: 145,
      },
      {
        id: "ap-studio",
        label: "Studio AP",
        kind: "access-point",
        status: "online",
        x: 460,
        y: 200,
        detail: "Workspace access point overlapping with the lobby for seamless client roaming.",
        zone: "Studio",
        role: "access",
        band: "tri-band",
        channel: "6 GHz ch 21",
        coverageRadius: 160,
      },
      {
        id: "ap-cafe",
        label: "Cafe AP",
        kind: "access-point",
        status: "degraded",
        x: 700,
        y: 250,
        detail: "Cafe access point with lighter signal quality near the edges of the floor.",
        zone: "Cafe",
        role: "access",
        band: "dual-band",
        channel: "5 GHz ch 157",
        coverageRadius: 135,
      },
      {
        id: "wlc-office",
        label: "WLAN Controller",
        kind: "controller",
        status: "online",
        x: 520,
        y: 95,
        detail:
          "Central controller coordinating AP policy and client handoff across the office floor.",
        zone: "Core Closet",
        role: "control",
        band: "wired-only",
        channel: "Mgmt VLAN",
        coverageRadius: 0,
      },
      {
        id: "internet-edge",
        label: "Internet Edge",
        kind: "gateway",
        status: "online",
        x: 825,
        y: 120,
        detail: "Gateway that terminates the office uplink and provides external reachability.",
        zone: "Core Closet",
        role: "edge",
        band: "wired-only",
        channel: "WAN",
        coverageRadius: 0,
      },
      {
        id: "tablet-01",
        label: "Designer Tablet",
        kind: "client",
        status: "online",
        x: 390,
        y: 325,
        detail: "Mobile user device moving from the lobby toward the studio and cafe overlap zone.",
        zone: "Studio Walkway",
        role: "endpoint",
        band: "6-ghz",
        channel: "Client auto",
        coverageRadius: 0,
      },
    ],
    connections: [
      {
        id: "tablet-01-ap-lobby",
        from: "tablet-01",
        to: "ap-lobby",
        kind: "wireless-link",
        strength: "medium",
        rssi: -63,
        throughputMbps: 310,
      },
      {
        id: "tablet-01-ap-studio",
        from: "tablet-01",
        to: "ap-studio",
        kind: "wireless-link",
        strength: "strong",
        rssi: -52,
        throughputMbps: 620,
      },
      {
        id: "tablet-01-ap-cafe",
        from: "tablet-01",
        to: "ap-cafe",
        kind: "wireless-link",
        strength: "weak",
        rssi: -74,
        throughputMbps: 140,
      },
      {
        id: "ap-lobby-wlc-office",
        from: "ap-lobby",
        to: "wlc-office",
        kind: "wired-uplink",
        strength: "strong",
        rssi: 0,
        throughputMbps: 1000,
      },
      {
        id: "ap-studio-wlc-office",
        from: "ap-studio",
        to: "wlc-office",
        kind: "wired-uplink",
        strength: "strong",
        rssi: 0,
        throughputMbps: 1000,
      },
      {
        id: "ap-cafe-wlc-office",
        from: "ap-cafe",
        to: "wlc-office",
        kind: "wired-uplink",
        strength: "medium",
        rssi: 0,
        throughputMbps: 600,
      },
      {
        id: "wlc-office-internet-edge",
        from: "wlc-office",
        to: "internet-edge",
        kind: "mesh-backhaul",
        strength: "strong",
        rssi: 0,
        throughputMbps: 1200,
      },
    ],
  },
  {
    id: "warehouse-coverage",
    name: "Warehouse Coverage",
    summary:
      "Warehouse scanners compare aisle and loading dock coverage to keep inventory traffic connected.",
    devices: [
      {
        id: "ap-aisle-a",
        label: "Aisle A AP",
        kind: "access-point",
        status: "online",
        x: 210,
        y: 150,
        detail: "Access point covering the first warehouse aisle cluster.",
        zone: "Aisle A",
        role: "access",
        band: "dual-band",
        channel: "5 GHz ch 36",
        coverageRadius: 150,
      },
      {
        id: "ap-dock",
        label: "Dock AP",
        kind: "access-point",
        status: "online",
        x: 505,
        y: 190,
        detail: "Loading dock AP balancing handheld scanners and staging devices.",
        zone: "Loading Dock",
        role: "access",
        band: "tri-band",
        channel: "6 GHz ch 37",
        coverageRadius: 175,
      },
      {
        id: "ap-cold",
        label: "Cold Storage AP",
        kind: "access-point",
        status: "degraded",
        x: 780,
        y: 235,
        detail: "Cold storage AP with signal attenuation from insulated walls.",
        zone: "Cold Storage",
        role: "access",
        band: "dual-band",
        channel: "5 GHz ch 149",
        coverageRadius: 120,
      },
      {
        id: "warehouse-gateway",
        label: "Warehouse Gateway",
        kind: "gateway",
        status: "online",
        x: 865,
        y: 105,
        detail: "Gateway aggregating dock and warehouse traffic toward upstream services.",
        zone: "Network Rack",
        role: "edge",
        band: "wired-only",
        channel: "WAN",
        coverageRadius: 0,
      },
      {
        id: "scanner-01",
        label: "Forklift Scanner",
        kind: "client",
        status: "online",
        x: 610,
        y: 355,
        detail: "Roaming scanner shifting between the dock and cold storage boundary.",
        zone: "Dock Transit",
        role: "endpoint",
        band: "dual-band",
        channel: "Client auto",
        coverageRadius: 0,
      },
    ],
    connections: [
      {
        id: "scanner-01-ap-aisle-a",
        from: "scanner-01",
        to: "ap-aisle-a",
        kind: "wireless-link",
        strength: "weak",
        rssi: -76,
        throughputMbps: 125,
      },
      {
        id: "scanner-01-ap-dock",
        from: "scanner-01",
        to: "ap-dock",
        kind: "wireless-link",
        strength: "strong",
        rssi: -55,
        throughputMbps: 510,
      },
      {
        id: "scanner-01-ap-cold",
        from: "scanner-01",
        to: "ap-cold",
        kind: "wireless-link",
        strength: "medium",
        rssi: -66,
        throughputMbps: 250,
      },
      {
        id: "ap-aisle-a-ap-dock",
        from: "ap-aisle-a",
        to: "ap-dock",
        kind: "mesh-backhaul",
        strength: "medium",
        rssi: 0,
        throughputMbps: 780,
      },
      {
        id: "ap-dock-warehouse-gateway",
        from: "ap-dock",
        to: "warehouse-gateway",
        kind: "wired-uplink",
        strength: "strong",
        rssi: 0,
        throughputMbps: 1000,
      },
      {
        id: "ap-cold-warehouse-gateway",
        from: "ap-cold",
        to: "warehouse-gateway",
        kind: "wired-uplink",
        strength: "medium",
        rssi: 0,
        throughputMbps: 450,
      },
    ],
  },
]
