import { SdnTopology } from "./sdn.models"

export const SDN_TOPOLOGIES: SdnTopology[] = [
  {
    id: "controller-path-override",
    name: "Controller Path Override",
    summary:
      "A central SDN controller can switch the same application flow between a private fabric path and an inspected compliance path.",
    defaultPolicyId: "latency-optimized",
    policies: [
      {
        id: "latency-optimized",
        label: "Latency optimized",
        summary: "Prefer the lowest-latency managed fabric path.",
        intent: "latency",
        overrideReason: "Controller keeps traffic on the private fabric to minimize delay.",
      },
      {
        id: "compliance-enforced",
        label: "Compliance enforced",
        summary: "Steer flows through the inspected edge before they reach shared services.",
        intent: "compliance",
        overrideReason:
          "Controller reroutes the flow through the inspected edge to satisfy compliance policy.",
      },
      {
        id: "resilience-priority",
        label: "Resilience priority",
        summary: "Prefer the managed fabric path tagged for controller resilience.",
        intent: "resilience",
        overrideReason:
          "Controller holds traffic on the managed fabric because it provides the strongest resilient path.",
      },
    ],
    devices: [
      {
        id: "branch-user",
        label: "Branch User Edge",
        kind: "edge-switch",
        status: "online",
        x: 120,
        y: 300,
        detail:
          "User-facing edge switch whose flow can be steered by the SDN controller across multiple transport intents.",
        site: "Branch User Edge",
        region: "Campus West",
        tier: "edge",
        role: "site",
      },
      {
        id: "fabric-core",
        label: "Fabric Core",
        kind: "fabric-switch",
        status: "online",
        x: 720,
        y: 240,
        detail:
          "Policy-enforced fabric switch that receives controller decisions and forwards traffic toward shared services.",
        site: "Fabric Core",
        region: "Campus East",
        tier: "fabric",
        role: "site",
      },
      {
        id: "sdn-controller",
        label: "Central Controller",
        kind: "controller",
        status: "online",
        x: 460,
        y: 90,
        detail:
          "Central control-plane node that applies SDN policy and overrides the forwarding path when intent changes.",
        site: "Controller Cluster",
        region: "Operations",
        tier: "control",
        role: "controller",
      },
      {
        id: "app-cluster",
        label: "App Cluster",
        kind: "service-endpoint",
        status: "online",
        x: 900,
        y: 190,
        detail:
          "Shared application service reached after the controller selects the preferred forwarding path.",
        site: "Application Cluster",
        region: "Services",
        tier: "service",
        role: "service",
      },
      {
        id: "audit-vault",
        label: "Audit Vault",
        kind: "service-endpoint",
        status: "online",
        x: 900,
        y: 380,
        detail:
          "Compliance-sensitive service that demonstrates controller steering through an inspected path.",
        site: "Audit Vault",
        region: "Services",
        tier: "service",
        role: "service",
      },
      {
        id: "private-edge",
        label: "Private Fabric Edge",
        kind: "uplink",
        status: "online",
        x: 320,
        y: 185,
        detail: "Managed private transport edge used by the default low-latency fabric policy.",
        site: "Private Fabric",
        region: "Transit",
        tier: "fabric",
        role: "transit",
      },
      {
        id: "internet-edge",
        label: "Inspected Internet Edge",
        kind: "uplink",
        status: "online",
        x: 320,
        y: 415,
        detail: "Inspected edge path that the controller selects for compliance-driven traffic.",
        site: "Inspected Edge",
        region: "Transit",
        tier: "fabric",
        role: "transit",
      },
    ],
    connections: [
      {
        id: "branch-user-private-edge",
        from: "branch-user",
        to: "private-edge",
        kind: "overlay-link",
        strength: "strong",
        distanceKm: 4,
        latencyMs: 16,
        jitterMs: 2,
        packetLossPct: 0.1,
        bandwidthMbps: 700,
        carrier: "Private Fabric",
        costUsd: 2300,
        priority: 1,
        intents: ["latency", "resilience"],
      },
      {
        id: "private-edge-fabric-core",
        from: "private-edge",
        to: "fabric-core",
        kind: "fabric-link",
        strength: "strong",
        distanceKm: 6,
        latencyMs: 20,
        jitterMs: 3,
        packetLossPct: 0.1,
        bandwidthMbps: 700,
        carrier: "Private Fabric",
        costUsd: 2100,
        priority: 1,
        intents: ["latency", "resilience"],
      },
      {
        id: "branch-user-internet-edge",
        from: "branch-user",
        to: "internet-edge",
        kind: "overlay-link",
        strength: "medium",
        distanceKm: 5,
        latencyMs: 24,
        jitterMs: 4,
        packetLossPct: 0.2,
        bandwidthMbps: 520,
        carrier: "Inspected Edge",
        costUsd: 900,
        priority: 1,
        intents: ["compliance"],
      },
      {
        id: "internet-edge-fabric-core",
        from: "internet-edge",
        to: "fabric-core",
        kind: "backup-link",
        strength: "strong",
        distanceKm: 7,
        latencyMs: 27,
        jitterMs: 5,
        packetLossPct: 0.2,
        bandwidthMbps: 520,
        carrier: "Inspected Edge",
        costUsd: 950,
        priority: 1,
        intents: ["compliance"],
      },
      {
        id: "fabric-core-app-cluster",
        from: "fabric-core",
        to: "app-cluster",
        kind: "direct-link",
        strength: "strong",
        distanceKm: 3,
        latencyMs: 8,
        jitterMs: 1,
        packetLossPct: 0,
        bandwidthMbps: 1000,
        carrier: "East-West Fabric",
        costUsd: 1100,
        priority: 1,
        intents: ["latency", "compliance", "resilience"],
      },
      {
        id: "fabric-core-audit-vault",
        from: "fabric-core",
        to: "audit-vault",
        kind: "direct-link",
        strength: "strong",
        distanceKm: 4,
        latencyMs: 12,
        jitterMs: 2,
        packetLossPct: 0,
        bandwidthMbps: 850,
        carrier: "Audit Segment",
        costUsd: 900,
        priority: 1,
        intents: ["compliance", "resilience"],
      },
    ],
  },
  {
    id: "controller-resilience-reroute",
    name: "Controller Resilience Reroute",
    summary:
      "A controller keeps branch traffic on the resilient overlay instead of the shorter but less stable primary route.",
    defaultPolicyId: "resilience-priority",
    policies: [
      {
        id: "latency-optimized",
        label: "Latency optimized",
        summary: "Prefer the shortest available transport.",
        intent: "latency",
        overrideReason: "Controller prefers the shortest overlay for interactive traffic.",
      },
      {
        id: "resilience-priority",
        label: "Resilience priority",
        summary: "Prefer the strongest redundant overlay for continuity.",
        intent: "resilience",
        overrideReason:
          "Controller overrides the shorter route to keep traffic on the resilient overlay.",
      },
    ],
    devices: [
      {
        id: "branch-west",
        label: "Branch West Edge",
        kind: "edge-switch",
        status: "online",
        x: 125,
        y: 310,
        detail:
          "Branch edge whose controller policy can keep traffic on a safer overlay instead of the shorter primary route.",
        site: "Branch West",
        region: "Region West",
        tier: "edge",
        role: "site",
      },
      {
        id: "branch-east",
        label: "Branch East Fabric",
        kind: "fabric-switch",
        status: "online",
        x: 745,
        y: 220,
        detail: "Remote fabric switch that terminates the controller-selected overlay path.",
        site: "Branch East",
        region: "Region East",
        tier: "fabric",
        role: "site",
      },
      {
        id: "analytics-pod",
        label: "Analytics Pod",
        kind: "service-endpoint",
        status: "online",
        x: 920,
        y: 280,
        detail:
          "Analytics service that remains reachable even when the controller reroutes to a different overlay.",
        site: "Analytics Pod",
        region: "Services",
        tier: "service",
        role: "service",
      },
      {
        id: "noc-controller",
        label: "NOC Controller",
        kind: "controller",
        status: "online",
        x: 450,
        y: 80,
        detail: "Network operations controller that enforces the resilience-first SDN intent.",
        site: "NOC Controller",
        region: "Operations",
        tier: "control",
        role: "controller",
      },
      {
        id: "latency-overlay",
        label: "Primary Overlay",
        kind: "uplink",
        status: "degraded",
        x: 325,
        y: 190,
        detail: "Shorter overlay that the controller can avoid when resilience policy is active.",
        site: "Primary Overlay",
        region: "Transit",
        tier: "fabric",
        role: "transit",
      },
      {
        id: "resilient-overlay",
        label: "Resilient Overlay",
        kind: "uplink",
        status: "online",
        x: 345,
        y: 420,
        detail: "Longer but more stable overlay used when the controller prioritizes continuity.",
        site: "Resilient Overlay",
        region: "Transit",
        tier: "fabric",
        role: "transit",
      },
    ],
    connections: [
      {
        id: "branch-west-latency-overlay",
        from: "branch-west",
        to: "latency-overlay",
        kind: "overlay-link",
        strength: "medium",
        distanceKm: 4,
        latencyMs: 12,
        jitterMs: 4,
        packetLossPct: 0.3,
        bandwidthMbps: 650,
        carrier: "Primary Overlay",
        costUsd: 1500,
        priority: 1,
        intents: ["latency"],
      },
      {
        id: "latency-overlay-branch-east",
        from: "latency-overlay",
        to: "branch-east",
        kind: "fabric-link",
        strength: "medium",
        distanceKm: 5,
        latencyMs: 13,
        jitterMs: 4,
        packetLossPct: 0.3,
        bandwidthMbps: 650,
        carrier: "Primary Overlay",
        costUsd: 1550,
        priority: 1,
        intents: ["latency"],
      },
      {
        id: "branch-west-resilient-overlay",
        from: "branch-west",
        to: "resilient-overlay",
        kind: "overlay-link",
        strength: "strong",
        distanceKm: 7,
        latencyMs: 19,
        jitterMs: 2,
        packetLossPct: 0.1,
        bandwidthMbps: 800,
        carrier: "Resilient Overlay",
        costUsd: 1700,
        priority: 1,
        intents: ["resilience"],
      },
      {
        id: "resilient-overlay-branch-east",
        from: "resilient-overlay",
        to: "branch-east",
        kind: "backup-link",
        strength: "strong",
        distanceKm: 8,
        latencyMs: 21,
        jitterMs: 2,
        packetLossPct: 0.1,
        bandwidthMbps: 800,
        carrier: "Resilient Overlay",
        costUsd: 1750,
        priority: 1,
        intents: ["resilience"],
      },
      {
        id: "branch-east-analytics-pod",
        from: "branch-east",
        to: "analytics-pod",
        kind: "direct-link",
        strength: "strong",
        distanceKm: 3,
        latencyMs: 6,
        jitterMs: 1,
        packetLossPct: 0,
        bandwidthMbps: 950,
        carrier: "Service Fabric",
        costUsd: 1200,
        priority: 1,
        intents: ["latency", "resilience"],
      },
    ],
  },
]
