import { AcnTopology } from "./acn.models"

export const ACN_TOPOLOGIES: AcnTopology[] = [
  {
    id: "default-deny-with-exception",
    name: "Default Deny With Exception",
    summary:
      "A branch client reaches an approved business service through a firewall exception while unapproved access remains blocked by default deny policy.",
    defaultPolicyId: "allow-business-crm",
    policies: [
      {
        id: "allow-business-crm",
        label: "Allow business CRM",
        summary:
          "Permit branch users in the user zone to reach the CRM service in the business zone through the access firewall.",
        sourceZone: "user",
        destinationZone: "business",
        action: "allow",
        violationReason: "no-violation",
        priority: 1,
      },
      {
        id: "deny-user-payroll",
        label: "Deny payroll access",
        summary:
          "Block direct user access into the payroll zone unless an explicit exception exists.",
        sourceZone: "user",
        destinationZone: "restricted",
        action: "block",
        violationReason: "explicit-block",
        priority: 2,
      },
    ],
    devices: [
      {
        id: "branch-laptop",
        label: "Branch Laptop",
        kind: "source-host",
        status: "online",
        x: 140,
        y: 220,
        detail: "Employee endpoint originating approved business traffic from the user zone.",
        site: "Branch 22",
        region: "User Access Layer",
        tier: "client",
        role: "source",
        zone: "user",
        rack: "USR-22",
      },
      {
        id: "guest-tablet",
        label: "Guest Tablet",
        kind: "source-host",
        status: "online",
        x: 140,
        y: 400,
        detail: "Guest endpoint sharing the edge but restricted to a narrower security posture.",
        site: "Branch 22",
        region: "User Access Layer",
        tier: "client",
        role: "source",
        zone: "guest",
        rack: "GST-22",
      },
      {
        id: "branch-firewall",
        label: "Branch Firewall",
        kind: "access-firewall",
        status: "online",
        x: 380,
        y: 300,
        detail: "Zone firewall enforcing default deny posture and explicit exception rules.",
        site: "Branch 22",
        region: "Enforcement Tier",
        tier: "enforcement",
        role: "security",
        zone: "inspection",
        rack: "FW-22",
      },
      {
        id: "crm-service",
        label: "CRM Service",
        kind: "service-host",
        status: "online",
        x: 760,
        y: 220,
        detail:
          "Approved business application reachable from the user zone through the firewall exception.",
        site: "Core Services",
        region: "Business Services",
        tier: "service",
        role: "service",
        zone: "business",
        rack: "CRM-1",
        cluster: "crm",
      },
      {
        id: "payroll-service",
        label: "Payroll Service",
        kind: "service-host",
        status: "online",
        x: 760,
        y: 400,
        detail:
          "Restricted application that demonstrates explicit policy denial for unauthorized zones.",
        site: "Core Services",
        region: "Restricted Services",
        tier: "service",
        role: "service",
        zone: "restricted",
        rack: "PAY-1",
        cluster: "payroll",
      },
      {
        id: "soc-console",
        label: "SOC Console",
        kind: "management-station",
        status: "online",
        x: 760,
        y: 540,
        detail:
          "Operations console used to inspect policy state without participating in the user service path.",
        site: "Security Operations",
        region: "Operations Tier",
        tier: "operations",
        role: "management",
        zone: "operations",
        rack: "SOC-1",
      },
    ],
    connections: [
      {
        id: "branch-laptop-branch-firewall",
        from: "branch-laptop",
        to: "branch-firewall",
        kind: "allowed-link",
        strength: "strong",
        distanceKm: 1,
        latencyMs: 1,
        jitterMs: 0,
        packetLossPct: 0,
        throughputMBps: 9000,
        utilizationPct: 38,
        carrier: "Branch LAN",
        costUsd: 140,
        priority: 1,
        action: "allow",
        ruleId: "allow-business-crm",
        sourceZone: "user",
        destinationZone: "inspection",
      },
      {
        id: "guest-tablet-branch-firewall",
        from: "guest-tablet",
        to: "branch-firewall",
        kind: "inspection-link",
        strength: "medium",
        distanceKm: 1,
        latencyMs: 2,
        jitterMs: 1,
        packetLossPct: 0,
        throughputMBps: 6200,
        utilizationPct: 44,
        carrier: "Guest LAN",
        costUsd: 120,
        priority: 2,
        action: "inspect",
        ruleId: "allow-business-crm",
        sourceZone: "guest",
        destinationZone: "inspection",
      },
      {
        id: "branch-firewall-crm-service",
        from: "branch-firewall",
        to: "crm-service",
        kind: "allowed-link",
        strength: "strong",
        distanceKm: 18,
        latencyMs: 5,
        jitterMs: 1,
        packetLossPct: 0.1,
        throughputMBps: 7800,
        utilizationPct: 46,
        carrier: "Policy Backbone",
        costUsd: 520,
        priority: 1,
        action: "allow",
        ruleId: "allow-business-crm",
        sourceZone: "inspection",
        destinationZone: "business",
      },
      {
        id: "branch-firewall-payroll-service",
        from: "branch-firewall",
        to: "payroll-service",
        kind: "blocked-link",
        strength: "strong",
        distanceKm: 20,
        latencyMs: 6,
        jitterMs: 1,
        packetLossPct: 0,
        throughputMBps: 0,
        utilizationPct: 0,
        carrier: "Restricted Backbone",
        costUsd: 520,
        priority: 3,
        action: "block",
        ruleId: "deny-user-payroll",
        sourceZone: "inspection",
        destinationZone: "restricted",
      },
      {
        id: "branch-firewall-soc-console",
        from: "branch-firewall",
        to: "soc-console",
        kind: "inspection-link",
        strength: "medium",
        distanceKm: 24,
        latencyMs: 8,
        jitterMs: 2,
        packetLossPct: 0,
        throughputMBps: 5200,
        utilizationPct: 30,
        carrier: "Operations Backbone",
        costUsd: 330,
        priority: 2,
        action: "inspect",
        ruleId: "allow-business-crm",
        sourceZone: "inspection",
        destinationZone: "operations",
      },
    ],
  },
  {
    id: "inspection-required",
    name: "Inspection Required",
    summary:
      "Sensitive traffic remains reachable, but the path is forced through a degraded inspection chain before the service can be accessed.",
    defaultPolicyId: "inspect-finance-app",
    policies: [
      {
        id: "inspect-finance-app",
        label: "Inspect finance app",
        summary:
          "Permit finance users to reach the finance application only through the inline inspection chain.",
        sourceZone: "finance-user",
        destinationZone: "finance-service",
        action: "inspect",
        violationReason: "no-violation",
        priority: 1,
      },
      {
        id: "block-operations-admin",
        label: "Block operations admin",
        summary: "Deny direct user-originated access into the admin tools zone.",
        sourceZone: "finance-user",
        destinationZone: "admin",
        action: "block",
        violationReason: "zone-mismatch",
        priority: 2,
      },
    ],
    devices: [
      {
        id: "finance-workstation",
        label: "Finance Workstation",
        kind: "source-host",
        status: "online",
        x: 140,
        y: 240,
        detail:
          "User endpoint that may access the finance application only through inspected traffic policy.",
        site: "HQ Floor 5",
        region: "Finance User Zone",
        tier: "client",
        role: "source",
        zone: "finance-user",
        rack: "FIN-5",
      },
      {
        id: "backup-workstation",
        label: "Backup Workstation",
        kind: "source-host",
        status: "online",
        x: 140,
        y: 420,
        detail:
          "Secondary user endpoint that can inherit the inspected path if the primary client goes offline.",
        site: "HQ Floor 5",
        region: "Finance User Zone",
        tier: "client",
        role: "source",
        zone: "finance-user",
        rack: "FIN-6",
      },
      {
        id: "inspection-firewall",
        label: "Inspection Firewall",
        kind: "access-firewall",
        status: "degraded",
        x: 380,
        y: 240,
        detail: "Inline firewall enforcing inspection before the finance service can be reached.",
        site: "HQ Security Edge",
        region: "Enforcement Tier",
        tier: "enforcement",
        role: "security",
        zone: "inspection",
        rack: "FW-HQ",
      },
      {
        id: "inspection-proxy",
        label: "Inspection Proxy",
        kind: "management-station",
        status: "online",
        x: 560,
        y: 360,
        detail:
          "Inline inspection hop providing additional analysis before traffic reaches the finance service.",
        site: "HQ Security Edge",
        region: "Operations Tier",
        tier: "operations",
        role: "management",
        zone: "inspection",
        rack: "PRX-HQ",
      },
      {
        id: "finance-app",
        label: "Finance App",
        kind: "service-host",
        status: "online",
        x: 780,
        y: 240,
        detail:
          "Sensitive service that remains reachable only when inspection policy is satisfied.",
        site: "Core Services",
        region: "Finance Services",
        tier: "service",
        role: "service",
        zone: "finance-service",
        rack: "FIN-SVC",
        cluster: "finance",
      },
      {
        id: "admin-console",
        label: "Admin Console",
        kind: "service-host",
        status: "online",
        x: 780,
        y: 440,
        detail: "Administrative service intentionally blocked from direct user-zone access.",
        site: "Core Services",
        region: "Administrative Services",
        tier: "service",
        role: "service",
        zone: "admin",
        rack: "ADM-SVC",
        cluster: "admin",
      },
    ],
    connections: [
      {
        id: "finance-workstation-inspection-firewall",
        from: "finance-workstation",
        to: "inspection-firewall",
        kind: "inspection-link",
        strength: "medium",
        distanceKm: 1,
        latencyMs: 2,
        jitterMs: 1,
        packetLossPct: 0,
        throughputMBps: 6800,
        utilizationPct: 49,
        carrier: "HQ Access LAN",
        costUsd: 150,
        priority: 1,
        action: "inspect",
        ruleId: "inspect-finance-app",
        sourceZone: "finance-user",
        destinationZone: "inspection",
      },
      {
        id: "backup-workstation-inspection-firewall",
        from: "backup-workstation",
        to: "inspection-firewall",
        kind: "inspection-link",
        strength: "medium",
        distanceKm: 1,
        latencyMs: 2,
        jitterMs: 1,
        packetLossPct: 0,
        throughputMBps: 6400,
        utilizationPct: 42,
        carrier: "HQ Access LAN",
        costUsd: 150,
        priority: 2,
        action: "inspect",
        ruleId: "inspect-finance-app",
        sourceZone: "finance-user",
        destinationZone: "inspection",
      },
      {
        id: "inspection-firewall-inspection-proxy",
        from: "inspection-firewall",
        to: "inspection-proxy",
        kind: "inspection-link",
        strength: "medium",
        distanceKm: 8,
        latencyMs: 6,
        jitterMs: 2,
        packetLossPct: 0.1,
        throughputMBps: 5900,
        utilizationPct: 64,
        carrier: "Inspection Fabric",
        costUsd: 410,
        priority: 1,
        action: "inspect",
        ruleId: "inspect-finance-app",
        sourceZone: "inspection",
        destinationZone: "inspection",
      },
      {
        id: "inspection-proxy-finance-app",
        from: "inspection-proxy",
        to: "finance-app",
        kind: "allowed-link",
        strength: "strong",
        distanceKm: 10,
        latencyMs: 4,
        jitterMs: 1,
        packetLossPct: 0,
        throughputMBps: 7200,
        utilizationPct: 52,
        carrier: "Service Backbone",
        costUsd: 470,
        priority: 1,
        action: "allow",
        ruleId: "inspect-finance-app",
        sourceZone: "inspection",
        destinationZone: "finance-service",
      },
      {
        id: "inspection-firewall-admin-console",
        from: "inspection-firewall",
        to: "admin-console",
        kind: "blocked-link",
        strength: "strong",
        distanceKm: 12,
        latencyMs: 5,
        jitterMs: 1,
        packetLossPct: 0,
        throughputMBps: 0,
        utilizationPct: 0,
        carrier: "Admin Backbone",
        costUsd: 430,
        priority: 3,
        action: "block",
        ruleId: "block-operations-admin",
        sourceZone: "inspection",
        destinationZone: "admin",
      },
    ],
  },
]
