import { NmoTopology } from "./nmo.models"

export const NMO_TOPOLOGIES: NmoTopology[] = [
  {
    id: "detect-only-failure",
    name: "Detect Only Failure",
    summary:
      "Monitoring detects a degraded primary route and alerts the operator, but detect-only policy holds traffic on the primary path instead of activating the backup gateway.",
    defaultPolicyId: "observe-and-hold",
    policies: [
      {
        id: "observe-and-hold",
        label: "Observe and hold",
        summary:
          "Report health issues but keep traffic on the current primary route while the path remains serviceable.",
        mode: "detect-only",
        priority: 1,
      },
    ],
    devices: [
      {
        id: "branch-agent",
        label: "Branch Agent",
        kind: "managed-node",
        status: "online",
        x: 140,
        y: 260,
        detail:
          "Managed branch node sending business traffic into the monitored automation domain.",
        site: "Branch 12",
        region: "Edge Access",
        tier: "edge",
        role: "source",
        domain: "branch",
        rack: "BR-12",
      },
      {
        id: "metro-core",
        label: "Metro Core",
        kind: "managed-node",
        status: "degraded",
        x: 360,
        y: 260,
        detail:
          "Primary transit device under degraded health that still forwards traffic while the controller holds remediation.",
        site: "Metro Hub",
        region: "Core Transit",
        tier: "core",
        role: "transit",
        domain: "core",
        rack: "MC-4",
      },
      {
        id: "automation-controller",
        label: "Automation Controller",
        kind: "automation-controller",
        status: "online",
        x: 360,
        y: 80,
        detail:
          "Management plane controller that evaluates monitor alerts and decides whether to hold or reroute traffic.",
        site: "Ops Center",
        region: "Control Plane",
        tier: "control",
        role: "controller",
        domain: "automation",
        rack: "CTRL-1",
      },
      {
        id: "health-monitor",
        label: "Health Monitor",
        kind: "health-monitor",
        status: "online",
        x: 580,
        y: 80,
        detail: "Observability node emitting health alerts when primary infrastructure degrades.",
        site: "Ops Center",
        region: "Observability",
        tier: "observability",
        role: "monitor",
        domain: "monitoring",
        rack: "MON-1",
      },
      {
        id: "backup-gateway",
        label: "Backup Gateway",
        kind: "backup-gateway",
        status: "online",
        x: 580,
        y: 360,
        detail:
          "Standby transport gateway ready to take over if automation policy enables reroute.",
        site: "Transit POP",
        region: "Backup Transport",
        tier: "transport",
        role: "backup",
        domain: "backup",
        rack: "BKP-2",
      },
      {
        id: "erp-service",
        label: "ERP Service",
        kind: "service-endpoint",
        status: "online",
        x: 780,
        y: 260,
        detail:
          "Managed service endpoint reached through either the primary metro path or the backup gateway.",
        site: "Primary Region",
        region: "Service Tier",
        tier: "service",
        role: "service",
        domain: "enterprise-service",
        rack: "ERP-1",
        cluster: "erp",
      },
    ],
    connections: [
      {
        id: "branch-agent-metro-core",
        from: "branch-agent",
        to: "metro-core",
        kind: "primary-link",
        strength: "medium",
        distanceKm: 6,
        latencyMs: 4,
        jitterMs: 2,
        packetLossPct: 0.3,
        throughputMBps: 6200,
        utilizationPct: 78,
        carrier: "Metro Ethernet",
        costUsd: 340,
        priority: 1,
        health: "degraded",
        remediationAction: "hold-route",
        policyId: "observe-and-hold",
        notes: "Primary edge handoff remains available but degraded.",
      },
      {
        id: "metro-core-erp-service",
        from: "metro-core",
        to: "erp-service",
        kind: "primary-link",
        strength: "medium",
        distanceKm: 18,
        latencyMs: 7,
        jitterMs: 3,
        packetLossPct: 0.4,
        throughputMBps: 5900,
        utilizationPct: 82,
        carrier: "Metro Ethernet",
        costUsd: 480,
        priority: 1,
        health: "degraded",
        remediationAction: "hold-route",
        policyId: "observe-and-hold",
        notes: "Service remains reachable while the fault is investigated.",
      },
      {
        id: "branch-agent-backup-gateway",
        from: "branch-agent",
        to: "backup-gateway",
        kind: "backup-link",
        strength: "strong",
        distanceKm: 15,
        latencyMs: 6,
        jitterMs: 1,
        packetLossPct: 0.1,
        throughputMBps: 7000,
        utilizationPct: 34,
        carrier: "Backup MPLS",
        costUsd: 620,
        priority: 3,
        health: "healthy",
        remediationAction: "standby",
        policyId: "observe-and-hold",
        notes: "Backup path is warm but policy does not activate it.",
      },
      {
        id: "backup-gateway-erp-service",
        from: "backup-gateway",
        to: "erp-service",
        kind: "backup-link",
        strength: "strong",
        distanceKm: 20,
        latencyMs: 8,
        jitterMs: 1,
        packetLossPct: 0.1,
        throughputMBps: 6800,
        utilizationPct: 31,
        carrier: "Backup MPLS",
        costUsd: 610,
        priority: 3,
        health: "healthy",
        remediationAction: "standby",
        policyId: "observe-and-hold",
        notes: "Backup leg is healthy and ready but inactive.",
      },
      {
        id: "health-monitor-metro-core",
        from: "health-monitor",
        to: "metro-core",
        kind: "monitor-link",
        strength: "strong",
        distanceKm: 4,
        latencyMs: 2,
        jitterMs: 1,
        packetLossPct: 0,
        throughputMBps: 1500,
        utilizationPct: 16,
        carrier: "Telemetry Mesh",
        costUsd: 90,
        priority: 1,
        health: "healthy",
        remediationAction: "emit-alert",
        notes: "Monitor reports the degraded primary transport.",
      },
      {
        id: "automation-controller-metro-core",
        from: "automation-controller",
        to: "metro-core",
        kind: "control-link",
        strength: "strong",
        distanceKm: 4,
        latencyMs: 2,
        jitterMs: 1,
        packetLossPct: 0,
        throughputMBps: 1600,
        utilizationPct: 12,
        carrier: "Control Plane",
        costUsd: 100,
        priority: 1,
        health: "healthy",
        remediationAction: "await-approval",
        policyId: "observe-and-hold",
        notes: "Controller acknowledges the alert but holds reroute action.",
      },
      {
        id: "automation-controller-backup-gateway",
        from: "automation-controller",
        to: "backup-gateway",
        kind: "control-link",
        strength: "strong",
        distanceKm: 5,
        latencyMs: 2,
        jitterMs: 1,
        packetLossPct: 0,
        throughputMBps: 1600,
        utilizationPct: 14,
        carrier: "Control Plane",
        costUsd: 100,
        priority: 2,
        health: "healthy",
        remediationAction: "standby",
        policyId: "observe-and-hold",
        notes: "Controller keeps the backup gateway armed.",
      },
    ],
  },
  {
    id: "auto-failover",
    name: "Auto Failover",
    summary:
      "The automation policy detects a failed primary route, then drives traffic through the backup gateway and records the remediation action automatically.",
    defaultPolicyId: "auto-remediate",
    policies: [
      {
        id: "auto-remediate",
        label: "Auto remediate",
        summary:
          "When the primary route fails, activate the backup path automatically and expose the remediation state to the operator.",
        mode: "auto-failover",
        priority: 1,
      },
    ],
    devices: [
      {
        id: "branch-agent",
        label: "Branch Agent",
        kind: "managed-node",
        status: "online",
        x: 140,
        y: 260,
        detail:
          "Managed branch node that requires automated recovery to keep the service reachable.",
        site: "Branch 12",
        region: "Edge Access",
        tier: "edge",
        role: "source",
        domain: "branch",
        rack: "BR-12",
      },
      {
        id: "metro-core",
        label: "Metro Core",
        kind: "managed-node",
        status: "offline",
        x: 360,
        y: 260,
        detail:
          "Primary transit device that has failed, forcing orchestration to consider the backup transport.",
        site: "Metro Hub",
        region: "Core Transit",
        tier: "core",
        role: "transit",
        domain: "core",
        rack: "MC-4",
      },
      {
        id: "automation-controller",
        label: "Automation Controller",
        kind: "automation-controller",
        status: "online",
        x: 360,
        y: 80,
        detail:
          "Control plane automation node that applies failover policy when monitors confirm the primary path is down.",
        site: "Ops Center",
        region: "Control Plane",
        tier: "control",
        role: "controller",
        domain: "automation",
        rack: "CTRL-1",
      },
      {
        id: "health-monitor",
        label: "Health Monitor",
        kind: "health-monitor",
        status: "online",
        x: 580,
        y: 80,
        detail:
          "Observability node that confirms the primary transit failure and triggers controller evaluation.",
        site: "Ops Center",
        region: "Observability",
        tier: "observability",
        role: "monitor",
        domain: "monitoring",
        rack: "MON-1",
      },
      {
        id: "backup-gateway",
        label: "Backup Gateway",
        kind: "backup-gateway",
        status: "online",
        x: 580,
        y: 360,
        detail: "Alternate transport node promoted automatically when the primary route fails.",
        site: "Transit POP",
        region: "Backup Transport",
        tier: "transport",
        role: "backup",
        domain: "backup",
        rack: "BKP-2",
      },
      {
        id: "erp-service",
        label: "ERP Service",
        kind: "service-endpoint",
        status: "online",
        x: 780,
        y: 260,
        detail: "Critical application endpoint that remains reachable after automated failover.",
        site: "Primary Region",
        region: "Service Tier",
        tier: "service",
        role: "service",
        domain: "enterprise-service",
        rack: "ERP-1",
        cluster: "erp",
      },
    ],
    connections: [
      {
        id: "branch-agent-metro-core",
        from: "branch-agent",
        to: "metro-core",
        kind: "primary-link",
        strength: "weak",
        distanceKm: 6,
        latencyMs: 0,
        jitterMs: 0,
        packetLossPct: 100,
        throughputMBps: 0,
        utilizationPct: 0,
        carrier: "Metro Ethernet",
        costUsd: 340,
        priority: 1,
        health: "failed",
        remediationAction: "declare-failure",
        policyId: "auto-remediate",
        notes: "Primary edge handoff is down.",
      },
      {
        id: "metro-core-erp-service",
        from: "metro-core",
        to: "erp-service",
        kind: "primary-link",
        strength: "weak",
        distanceKm: 18,
        latencyMs: 0,
        jitterMs: 0,
        packetLossPct: 100,
        throughputMBps: 0,
        utilizationPct: 0,
        carrier: "Metro Ethernet",
        costUsd: 480,
        priority: 1,
        health: "failed",
        remediationAction: "declare-failure",
        policyId: "auto-remediate",
        notes: "Primary service leg is unavailable.",
      },
      {
        id: "branch-agent-backup-gateway",
        from: "branch-agent",
        to: "backup-gateway",
        kind: "backup-link",
        strength: "strong",
        distanceKm: 15,
        latencyMs: 6,
        jitterMs: 1,
        packetLossPct: 0.1,
        throughputMBps: 7100,
        utilizationPct: 37,
        carrier: "Backup MPLS",
        costUsd: 620,
        priority: 2,
        health: "healthy",
        remediationAction: "activate-backup",
        policyId: "auto-remediate",
        notes: "Backup ingress path is healthy.",
      },
      {
        id: "backup-gateway-erp-service",
        from: "backup-gateway",
        to: "erp-service",
        kind: "backup-link",
        strength: "strong",
        distanceKm: 20,
        latencyMs: 8,
        jitterMs: 2,
        packetLossPct: 0.1,
        throughputMBps: 6900,
        utilizationPct: 42,
        carrier: "Backup MPLS",
        costUsd: 610,
        priority: 2,
        health: "healthy",
        remediationAction: "activate-backup",
        policyId: "auto-remediate",
        notes: "Backup service leg is healthy.",
      },
      {
        id: "health-monitor-metro-core",
        from: "health-monitor",
        to: "metro-core",
        kind: "monitor-link",
        strength: "strong",
        distanceKm: 4,
        latencyMs: 2,
        jitterMs: 1,
        packetLossPct: 0,
        throughputMBps: 1500,
        utilizationPct: 19,
        carrier: "Telemetry Mesh",
        costUsd: 90,
        priority: 1,
        health: "healthy",
        remediationAction: "emit-alert",
        notes: "Monitor confirms total primary-path failure.",
      },
      {
        id: "automation-controller-metro-core",
        from: "automation-controller",
        to: "metro-core",
        kind: "control-link",
        strength: "strong",
        distanceKm: 4,
        latencyMs: 2,
        jitterMs: 1,
        packetLossPct: 0,
        throughputMBps: 1600,
        utilizationPct: 13,
        carrier: "Control Plane",
        costUsd: 100,
        priority: 1,
        health: "healthy",
        remediationAction: "issue-failover",
        policyId: "auto-remediate",
        notes: "Controller records remediation action against the failed node.",
      },
      {
        id: "automation-controller-backup-gateway",
        from: "automation-controller",
        to: "backup-gateway",
        kind: "control-link",
        strength: "strong",
        distanceKm: 5,
        latencyMs: 2,
        jitterMs: 1,
        packetLossPct: 0,
        throughputMBps: 1600,
        utilizationPct: 15,
        carrier: "Control Plane",
        costUsd: 100,
        priority: 1,
        health: "healthy",
        remediationAction: "promote-backup",
        policyId: "auto-remediate",
        notes: "Controller enables the backup gateway.",
      },
    ],
  },
]
