import { WanTopology } from "./wan.models"

export const WAN_TOPOLOGIES: WanTopology[] = [
  {
    id: "regional-failover",
    name: "Regional Failover",
    summary:
      "A branch reaches headquarters and shared services over a preferred MPLS path with internet backup.",
    devices: [
      {
        id: "branch-west",
        label: "Branch West",
        kind: "branch",
        status: "online",
        x: 120,
        y: 320,
        detail: "West branch site that prefers MPLS but can fail over to an internet VPN path.",
        site: "West Branch",
        region: "US West",
        tier: "branch",
        role: "site",
      },
      {
        id: "hq-core",
        label: "HQ Core",
        kind: "headquarters",
        status: "online",
        x: 760,
        y: 200,
        detail:
          "Headquarters hub that aggregates branch traffic and hands services toward the data center.",
        site: "Headquarters",
        region: "US Central",
        tier: "core",
        role: "site",
      },
      {
        id: "data-hub",
        label: "Data Hub",
        kind: "data-center",
        status: "online",
        x: 760,
        y: 385,
        detail: "Regional data-center platform hosting enterprise workloads behind the WAN core.",
        site: "Primary DC",
        region: "US Central",
        tier: "core",
        role: "service",
      },
      {
        id: "cloud-erp",
        label: "Cloud ERP",
        kind: "cloud",
        status: "online",
        x: 925,
        y: 290,
        detail:
          "Cloud-hosted enterprise platform reached through the data-center on the preferred route.",
        site: "ERP SaaS",
        region: "US East",
        tier: "cloud",
        role: "cloud",
      },
      {
        id: "carrier-mpls",
        label: "Carrier MPLS",
        kind: "provider-edge",
        status: "online",
        x: 325,
        y: 195,
        detail: "Provider edge for the primary managed WAN path.",
        site: "Carrier A",
        region: "Backbone",
        tier: "regional",
        role: "transit",
      },
      {
        id: "carrier-internet",
        label: "Internet Edge",
        kind: "provider-edge",
        status: "degraded",
        x: 345,
        y: 420,
        detail: "Internet VPN edge used as the backup WAN path during primary carrier degradation.",
        site: "Carrier B",
        region: "Backbone",
        tier: "regional",
        role: "transit",
      },
    ],
    connections: [
      {
        id: "branch-west-carrier-mpls",
        from: "branch-west",
        to: "carrier-mpls",
        kind: "mpls",
        strength: "strong",
        latencyMs: 18,
        jitterMs: 3,
        packetLossPct: 0.1,
        bandwidthMbps: 600,
        carrier: "Carrier A",
        costUsd: 2400,
        priority: 1,
      },
      {
        id: "carrier-mpls-hq-core",
        from: "carrier-mpls",
        to: "hq-core",
        kind: "mpls",
        strength: "strong",
        latencyMs: 24,
        jitterMs: 4,
        packetLossPct: 0.1,
        bandwidthMbps: 600,
        carrier: "Carrier A",
        costUsd: 2600,
        priority: 1,
      },
      {
        id: "branch-west-carrier-internet",
        from: "branch-west",
        to: "carrier-internet",
        kind: "internet-vpn",
        strength: "medium",
        latencyMs: 33,
        jitterMs: 8,
        packetLossPct: 0.6,
        bandwidthMbps: 350,
        carrier: "Carrier B",
        costUsd: 900,
        priority: 2,
      },
      {
        id: "carrier-internet-hq-core",
        from: "carrier-internet",
        to: "hq-core",
        kind: "backup-link",
        strength: "medium",
        latencyMs: 41,
        jitterMs: 11,
        packetLossPct: 0.9,
        bandwidthMbps: 300,
        carrier: "Carrier B",
        costUsd: 1000,
        priority: 2,
      },
      {
        id: "hq-core-data-hub",
        from: "hq-core",
        to: "data-hub",
        kind: "direct-connect",
        strength: "strong",
        latencyMs: 9,
        jitterMs: 1,
        packetLossPct: 0,
        bandwidthMbps: 1000,
        carrier: "Metro Fiber",
        costUsd: 1800,
        priority: 1,
      },
      {
        id: "data-hub-cloud-erp",
        from: "data-hub",
        to: "cloud-erp",
        kind: "direct-connect",
        strength: "strong",
        latencyMs: 13,
        jitterMs: 2,
        packetLossPct: 0,
        bandwidthMbps: 900,
        carrier: "Cloud Fabric",
        costUsd: 2300,
        priority: 1,
      },
    ],
  },
  {
    id: "hybrid-service-mesh",
    name: "Hybrid Service Mesh",
    summary:
      "Retail and disaster-recovery sites share a primary cloud path and a slower backup route.",
    devices: [
      {
        id: "retail-east",
        label: "Retail East",
        kind: "branch",
        status: "online",
        x: 115,
        y: 275,
        detail:
          "Retail site that consumes SaaS analytics and can pivot to disaster recovery when the primary path degrades.",
        site: "Retail East",
        region: "US East",
        tier: "branch",
        role: "site",
      },
      {
        id: "regional-hq",
        label: "Regional HQ",
        kind: "headquarters",
        status: "degraded",
        x: 430,
        y: 180,
        detail: "Regional aggregation point that still carries traffic but at reduced quality.",
        site: "Regional HQ",
        region: "US East",
        tier: "regional",
        role: "site",
      },
      {
        id: "dr-site",
        label: "DR Site",
        kind: "data-center",
        status: "online",
        x: 705,
        y: 165,
        detail:
          "Disaster-recovery data center available if the preferred cloud path cannot be maintained.",
        site: "DR Facility",
        region: "US South",
        tier: "core",
        role: "service",
      },
      {
        id: "analytics-cloud",
        label: "Analytics Cloud",
        kind: "cloud",
        status: "online",
        x: 865,
        y: 340,
        detail: "Preferred analytics platform reached over a low-latency direct cloud on-ramp.",
        site: "Analytics SaaS",
        region: "US East",
        tier: "cloud",
        role: "cloud",
      },
      {
        id: "carrier-regional",
        label: "Regional Carrier",
        kind: "provider-edge",
        status: "online",
        x: 285,
        y: 360,
        detail: "Primary regional WAN provider edge for retail connectivity.",
        site: "Carrier C",
        region: "Backbone",
        tier: "regional",
        role: "transit",
      },
      {
        id: "carrier-cloud",
        label: "Cloud Transit",
        kind: "provider-edge",
        status: "online",
        x: 625,
        y: 355,
        detail: "Cloud transit provider that offers the preferred direct cloud path.",
        site: "Carrier D",
        region: "Backbone",
        tier: "regional",
        role: "transit",
      },
    ],
    connections: [
      {
        id: "retail-east-carrier-regional",
        from: "retail-east",
        to: "carrier-regional",
        kind: "mpls",
        strength: "strong",
        latencyMs: 15,
        jitterMs: 4,
        packetLossPct: 0.2,
        bandwidthMbps: 450,
        carrier: "Carrier C",
        costUsd: 2100,
        priority: 1,
      },
      {
        id: "carrier-regional-regional-hq",
        from: "carrier-regional",
        to: "regional-hq",
        kind: "mpls",
        strength: "medium",
        latencyMs: 26,
        jitterMs: 6,
        packetLossPct: 0.4,
        bandwidthMbps: 450,
        carrier: "Carrier C",
        costUsd: 2200,
        priority: 1,
      },
      {
        id: "regional-hq-carrier-cloud",
        from: "regional-hq",
        to: "carrier-cloud",
        kind: "direct-connect",
        strength: "strong",
        latencyMs: 12,
        jitterMs: 2,
        packetLossPct: 0.1,
        bandwidthMbps: 700,
        carrier: "Carrier D",
        costUsd: 2800,
        priority: 1,
      },
      {
        id: "carrier-cloud-analytics-cloud",
        from: "carrier-cloud",
        to: "analytics-cloud",
        kind: "direct-connect",
        strength: "strong",
        latencyMs: 11,
        jitterMs: 2,
        packetLossPct: 0,
        bandwidthMbps: 700,
        carrier: "Carrier D",
        costUsd: 2900,
        priority: 1,
      },
      {
        id: "regional-hq-dr-site",
        from: "regional-hq",
        to: "dr-site",
        kind: "backup-link",
        strength: "medium",
        latencyMs: 31,
        jitterMs: 9,
        packetLossPct: 0.7,
        bandwidthMbps: 300,
        carrier: "Carrier E",
        costUsd: 1400,
        priority: 2,
      },
      {
        id: "dr-site-analytics-cloud",
        from: "dr-site",
        to: "analytics-cloud",
        kind: "internet-vpn",
        strength: "weak",
        latencyMs: 48,
        jitterMs: 14,
        packetLossPct: 1.2,
        bandwidthMbps: 200,
        carrier: "Carrier E",
        costUsd: 800,
        priority: 3,
      },
    ],
  },
]
