import { DcnTopology } from "./dcn.models"

export const DCN_TOPOLOGIES: DcnTopology[] = [
  {
    id: "leaf-spine-redundancy",
    name: "Leaf-Spine Redundancy",
    summary:
      "A compute workload reaches a shared service over a two-tier leaf-spine fabric, preferring the lower-latency spine while keeping an alternate path ready for fast failover.",
    policies: [
      {
        id: "preferred-spine-path",
        label: "Preferred spine path",
        summary:
          "Prefer the primary spine and only shift to the alternate fabric path when the preferred path degrades or fails.",
      },
    ],
    devices: [
      {
        id: "app-pod",
        label: "App Pod",
        kind: "compute-node",
        status: "online",
        x: 120,
        y: 220,
        detail:
          "Application workload that uses the leaf-spine fabric to reach shared services with predictable latency.",
        site: "Rack A12",
        region: "Compute Row A",
        tier: "workload",
        role: "compute",
        rack: "A12",
        cluster: "frontend",
      },
      {
        id: "batch-pod",
        label: "Batch Pod",
        kind: "compute-node",
        status: "online",
        x: 120,
        y: 400,
        detail:
          "Secondary compute workload that can continue reaching shared services if the primary workload goes offline.",
        site: "Rack A14",
        region: "Compute Row A",
        tier: "workload",
        role: "compute",
        rack: "A14",
        cluster: "batch",
      },
      {
        id: "leaf-compute",
        label: "Leaf Compute",
        kind: "leaf-switch",
        status: "online",
        x: 300,
        y: 300,
        detail:
          "Rack-facing leaf switch that aggregates compute hosts before forwarding traffic into the spine tier.",
        site: "Leaf Pair 1",
        region: "Leaf Tier",
        tier: "leaf",
        role: "leaf",
        rack: "Leaf-1",
      },
      {
        id: "spine-1",
        label: "Spine 1",
        kind: "spine-switch",
        status: "online",
        x: 520,
        y: 170,
        detail: "Primary spine with the shortest path through the DC fabric to shared services.",
        site: "Spine Pair",
        region: "Spine Tier",
        tier: "spine",
        role: "spine",
        rack: "Spine-1",
      },
      {
        id: "spine-2",
        label: "Spine 2",
        kind: "spine-switch",
        status: "online",
        x: 520,
        y: 430,
        detail:
          "Alternate spine that protects the fabric when the preferred spine or uplink is degraded.",
        site: "Spine Pair",
        region: "Spine Tier",
        tier: "spine",
        role: "spine",
        rack: "Spine-2",
      },
      {
        id: "leaf-services",
        label: "Leaf Services",
        kind: "leaf-switch",
        status: "online",
        x: 720,
        y: 300,
        detail:
          "Service-facing leaf switch that connects shared workloads to the leaf-spine fabric.",
        site: "Leaf Pair 2",
        region: "Leaf Tier",
        tier: "leaf",
        role: "leaf",
        rack: "Leaf-2",
      },
      {
        id: "orders-service",
        label: "Orders Service",
        kind: "service-node",
        status: "online",
        x: 900,
        y: 220,
        detail: "Shared application service reached over the preferred leaf-spine path.",
        site: "Rack S04",
        region: "Services Row",
        tier: "service",
        role: "service",
        rack: "S04",
        cluster: "orders",
      },
      {
        id: "analytics-service",
        label: "Analytics Service",
        kind: "service-node",
        status: "online",
        x: 900,
        y: 400,
        detail:
          "Secondary shared service that uses the same service leaf while keeping the dual-spine fabric intact.",
        site: "Rack S06",
        region: "Services Row",
        tier: "service",
        role: "service",
        rack: "S06",
        cluster: "analytics",
      },
    ],
    connections: [
      {
        id: "app-pod-leaf-compute",
        from: "app-pod",
        to: "leaf-compute",
        kind: "rack-link",
        strength: "strong",
        distanceKm: 1,
        latencyMs: 1,
        jitterMs: 0,
        packetLossPct: 0,
        throughputMBps: 18000,
        iops: 0,
        utilizationPct: 42,
        carrier: "Rack A12",
        costUsd: 200,
        priority: 1,
      },
      {
        id: "batch-pod-leaf-compute",
        from: "batch-pod",
        to: "leaf-compute",
        kind: "rack-link",
        strength: "strong",
        distanceKm: 1,
        latencyMs: 1,
        jitterMs: 0,
        packetLossPct: 0,
        throughputMBps: 15000,
        iops: 0,
        utilizationPct: 35,
        carrier: "Rack A14",
        costUsd: 200,
        priority: 1,
      },
      {
        id: "leaf-compute-spine-1",
        from: "leaf-compute",
        to: "spine-1",
        kind: "fabric-uplink",
        strength: "strong",
        distanceKm: 2,
        latencyMs: 2,
        jitterMs: 1,
        packetLossPct: 0,
        throughputMBps: 12000,
        iops: 0,
        utilizationPct: 46,
        carrier: "Fabric Blue",
        costUsd: 900,
        priority: 1,
      },
      {
        id: "leaf-compute-spine-2",
        from: "leaf-compute",
        to: "spine-2",
        kind: "backup-uplink",
        strength: "strong",
        distanceKm: 2,
        latencyMs: 4,
        jitterMs: 1,
        packetLossPct: 0,
        throughputMBps: 9000,
        iops: 0,
        utilizationPct: 31,
        carrier: "Fabric Amber",
        costUsd: 700,
        priority: 2,
      },
      {
        id: "spine-1-leaf-services",
        from: "spine-1",
        to: "leaf-services",
        kind: "fabric-uplink",
        strength: "strong",
        distanceKm: 2,
        latencyMs: 2,
        jitterMs: 1,
        packetLossPct: 0,
        throughputMBps: 12000,
        iops: 0,
        utilizationPct: 48,
        carrier: "Fabric Blue",
        costUsd: 900,
        priority: 1,
      },
      {
        id: "spine-2-leaf-services",
        from: "spine-2",
        to: "leaf-services",
        kind: "backup-uplink",
        strength: "strong",
        distanceKm: 2,
        latencyMs: 4,
        jitterMs: 1,
        packetLossPct: 0,
        throughputMBps: 9000,
        iops: 0,
        utilizationPct: 28,
        carrier: "Fabric Amber",
        costUsd: 700,
        priority: 2,
      },
      {
        id: "leaf-services-orders-service",
        from: "leaf-services",
        to: "orders-service",
        kind: "rack-link",
        strength: "strong",
        distanceKm: 1,
        latencyMs: 1,
        jitterMs: 0,
        packetLossPct: 0,
        throughputMBps: 16000,
        iops: 0,
        utilizationPct: 51,
        carrier: "Rack S04",
        costUsd: 220,
        priority: 1,
      },
      {
        id: "leaf-services-analytics-service",
        from: "leaf-services",
        to: "analytics-service",
        kind: "rack-link",
        strength: "strong",
        distanceKm: 1,
        latencyMs: 1,
        jitterMs: 0,
        packetLossPct: 0,
        throughputMBps: 14000,
        iops: 0,
        utilizationPct: 38,
        carrier: "Rack S06",
        costUsd: 220,
        priority: 1,
      },
    ],
  },
  {
    id: "spine-failover",
    name: "Spine Failover",
    summary:
      "A compute workload uses the preferred spine while it is degraded, then reroutes over the alternate spine when the preferred fabric path goes offline.",
    policies: [
      {
        id: "protect-service-reachability",
        label: "Protect service reachability",
        summary:
          "Keep the active service reachable even when the preferred spine path degrades or fails.",
      },
    ],
    devices: [
      {
        id: "web-pod",
        label: "Web Pod",
        kind: "compute-node",
        status: "online",
        x: 120,
        y: 230,
        detail:
          "User-facing web workload that depends on a resilient leaf-spine path to the API tier.",
        site: "Rack B02",
        region: "Compute Row B",
        tier: "workload",
        role: "compute",
        rack: "B02",
        cluster: "web",
      },
      {
        id: "worker-pod",
        label: "Worker Pod",
        kind: "compute-node",
        status: "online",
        x: 120,
        y: 410,
        detail:
          "Background worker workload that can take over service access if the primary compute path changes.",
        site: "Rack B06",
        region: "Compute Row B",
        tier: "workload",
        role: "compute",
        rack: "B06",
        cluster: "workers",
      },
      {
        id: "leaf-apps",
        label: "Leaf Apps",
        kind: "leaf-switch",
        status: "online",
        x: 300,
        y: 320,
        detail: "Leaf switch serving application racks on the compute side of the fabric.",
        site: "Leaf Pair 3",
        region: "Leaf Tier",
        tier: "leaf",
        role: "leaf",
        rack: "Leaf-3",
      },
      {
        id: "spine-east",
        label: "Spine East",
        kind: "spine-switch",
        status: "degraded",
        x: 520,
        y: 180,
        detail:
          "Preferred spine currently operating in a degraded state but still carrying the lowest-latency path.",
        site: "East Spine",
        region: "Spine Tier",
        tier: "spine",
        role: "spine",
        rack: "Spine-East",
      },
      {
        id: "spine-west",
        label: "Spine West",
        kind: "spine-switch",
        status: "online",
        x: 520,
        y: 450,
        detail:
          "Protected alternate spine that takes over when the east spine can no longer carry the service path.",
        site: "West Spine",
        region: "Spine Tier",
        tier: "spine",
        role: "spine",
        rack: "Spine-West",
      },
      {
        id: "leaf-api",
        label: "Leaf API",
        kind: "leaf-switch",
        status: "online",
        x: 720,
        y: 320,
        detail: "Destination-side leaf switch serving the API and queue services.",
        site: "Leaf Pair 4",
        region: "Leaf Tier",
        tier: "leaf",
        role: "leaf",
        rack: "Leaf-4",
      },
      {
        id: "payments-api",
        label: "Payments API",
        kind: "service-node",
        status: "online",
        x: 900,
        y: 230,
        detail: "Primary shared API workload that demonstrates degraded and failover DCN paths.",
        site: "Rack P04",
        region: "Services Row",
        tier: "service",
        role: "service",
        rack: "P04",
        cluster: "payments",
      },
      {
        id: "queue-service",
        label: "Queue Service",
        kind: "service-node",
        status: "online",
        x: 900,
        y: 410,
        detail:
          "Secondary service workload connected to the same service leaf and protected by both spines.",
        site: "Rack P06",
        region: "Services Row",
        tier: "service",
        role: "service",
        rack: "P06",
        cluster: "queue",
      },
    ],
    connections: [
      {
        id: "web-pod-leaf-apps",
        from: "web-pod",
        to: "leaf-apps",
        kind: "rack-link",
        strength: "strong",
        distanceKm: 1,
        latencyMs: 1,
        jitterMs: 0,
        packetLossPct: 0,
        throughputMBps: 16000,
        iops: 0,
        utilizationPct: 49,
        carrier: "Rack B02",
        costUsd: 210,
        priority: 1,
      },
      {
        id: "worker-pod-leaf-apps",
        from: "worker-pod",
        to: "leaf-apps",
        kind: "rack-link",
        strength: "strong",
        distanceKm: 1,
        latencyMs: 1,
        jitterMs: 0,
        packetLossPct: 0,
        throughputMBps: 15000,
        iops: 0,
        utilizationPct: 44,
        carrier: "Rack B06",
        costUsd: 210,
        priority: 1,
      },
      {
        id: "leaf-apps-spine-east",
        from: "leaf-apps",
        to: "spine-east",
        kind: "fabric-uplink",
        strength: "medium",
        distanceKm: 2,
        latencyMs: 2,
        jitterMs: 1,
        packetLossPct: 0.1,
        throughputMBps: 9000,
        iops: 0,
        utilizationPct: 72,
        carrier: "Fabric East",
        costUsd: 850,
        priority: 1,
      },
      {
        id: "leaf-apps-spine-west",
        from: "leaf-apps",
        to: "spine-west",
        kind: "backup-uplink",
        strength: "strong",
        distanceKm: 2,
        latencyMs: 4,
        jitterMs: 1,
        packetLossPct: 0,
        throughputMBps: 7600,
        iops: 0,
        utilizationPct: 36,
        carrier: "Fabric West",
        costUsd: 650,
        priority: 2,
      },
      {
        id: "spine-east-leaf-api",
        from: "spine-east",
        to: "leaf-api",
        kind: "fabric-uplink",
        strength: "medium",
        distanceKm: 2,
        latencyMs: 3,
        jitterMs: 1,
        packetLossPct: 0.1,
        throughputMBps: 9000,
        iops: 0,
        utilizationPct: 74,
        carrier: "Fabric East",
        costUsd: 850,
        priority: 1,
      },
      {
        id: "spine-west-leaf-api",
        from: "spine-west",
        to: "leaf-api",
        kind: "backup-uplink",
        strength: "strong",
        distanceKm: 2,
        latencyMs: 5,
        jitterMs: 1,
        packetLossPct: 0,
        throughputMBps: 7600,
        iops: 0,
        utilizationPct: 34,
        carrier: "Fabric West",
        costUsd: 650,
        priority: 2,
      },
      {
        id: "leaf-api-payments-api",
        from: "leaf-api",
        to: "payments-api",
        kind: "rack-link",
        strength: "strong",
        distanceKm: 1,
        latencyMs: 1,
        jitterMs: 0,
        packetLossPct: 0,
        throughputMBps: 15000,
        iops: 0,
        utilizationPct: 57,
        carrier: "Rack P04",
        costUsd: 230,
        priority: 1,
      },
      {
        id: "leaf-api-queue-service",
        from: "leaf-api",
        to: "queue-service",
        kind: "rack-link",
        strength: "strong",
        distanceKm: 1,
        latencyMs: 1,
        jitterMs: 0,
        packetLossPct: 0,
        throughputMBps: 13000,
        iops: 0,
        utilizationPct: 33,
        carrier: "Rack P06",
        costUsd: 230,
        priority: 1,
      },
    ],
  },
]
