import { ManTopology } from "./man.models"

export const MAN_TOPOLOGIES: ManTopology[] = [
  {
    id: "downtown-resilience-ring",
    name: "Downtown Resilience Ring",
    summary:
      "A downtown building reaches the metro core and shared services over primary fiber with metro ethernet backup.",
    devices: [
      {
        id: "north-tower",
        label: "North Tower",
        kind: "building-distribution",
        status: "online",
        x: 120,
        y: 250,
        detail:
          "Downtown building distribution node that prefers the primary metro fiber ring but can fail over to a metro ethernet handoff.",
        site: "North Tower",
        region: "Downtown",
        tier: "building",
        role: "site",
      },
      {
        id: "metro-core",
        label: "Metro Core",
        kind: "metro-core",
        status: "online",
        x: 720,
        y: 200,
        detail:
          "Central metro aggregation node that concentrates building traffic before handing shared services into the city core.",
        site: "Metro Core",
        region: "Central Loop",
        tier: "metro",
        role: "site",
      },
      {
        id: "south-campus",
        label: "South Campus",
        kind: "access-node",
        status: "online",
        x: 260,
        y: 410,
        detail:
          "Secondary metro building that stays on the same city ring and shares the core aggregation point.",
        site: "South Campus",
        region: "Riverfront",
        tier: "district",
        role: "site",
      },
      {
        id: "metro-dc",
        label: "Metro DC",
        kind: "service-handoff",
        status: "online",
        x: 900,
        y: 310,
        detail:
          "Metro data-center service handoff that terminates the preferred city path for shared enterprise services.",
        site: "Metro DC",
        region: "Central Loop",
        tier: "metro",
        role: "service",
      },
      {
        id: "provider-primary",
        label: "Fiber Ring A",
        kind: "provider-handoff",
        status: "online",
        x: 340,
        y: 180,
        detail: "Primary metro fiber provider handoff for the downtown resilience ring.",
        site: "Metro Fiber A",
        region: "Central Loop",
        tier: "metro",
        role: "transit",
      },
      {
        id: "provider-backup",
        label: "Metro Ethernet B",
        kind: "provider-handoff",
        status: "degraded",
        x: 380,
        y: 395,
        detail:
          "Backup metro ethernet provider that carries traffic during fiber ring degradation.",
        site: "Metro Ethernet B",
        region: "Riverfront",
        tier: "district",
        role: "transit",
      },
    ],
    connections: [
      {
        id: "north-tower-provider-primary",
        from: "north-tower",
        to: "provider-primary",
        kind: "metro-fiber",
        strength: "strong",
        distanceKm: 2,
        latencyMs: 4,
        jitterMs: 1,
        packetLossPct: 0,
        bandwidthMbps: 800,
        carrier: "Metro Fiber A",
        costUsd: 1800,
        priority: 1,
      },
      {
        id: "provider-primary-metro-core",
        from: "provider-primary",
        to: "metro-core",
        kind: "metro-fiber",
        strength: "strong",
        distanceKm: 4,
        latencyMs: 3,
        jitterMs: 1,
        packetLossPct: 0,
        bandwidthMbps: 800,
        carrier: "Metro Fiber A",
        costUsd: 1900,
        priority: 1,
      },
      {
        id: "north-tower-provider-backup",
        from: "north-tower",
        to: "provider-backup",
        kind: "metro-ethernet",
        strength: "medium",
        distanceKm: 5,
        latencyMs: 7,
        jitterMs: 2,
        packetLossPct: 0.2,
        bandwidthMbps: 450,
        carrier: "Metro Ethernet B",
        costUsd: 900,
        priority: 2,
      },
      {
        id: "provider-backup-metro-core",
        from: "provider-backup",
        to: "metro-core",
        kind: "backup-link",
        strength: "medium",
        distanceKm: 6,
        latencyMs: 8,
        jitterMs: 3,
        packetLossPct: 0.2,
        bandwidthMbps: 400,
        carrier: "Metro Ethernet B",
        costUsd: 950,
        priority: 2,
      },
      {
        id: "metro-core-south-campus",
        from: "metro-core",
        to: "south-campus",
        kind: "metro-fiber",
        strength: "strong",
        distanceKm: 7,
        latencyMs: 4,
        jitterMs: 1,
        packetLossPct: 0,
        bandwidthMbps: 700,
        carrier: "Civic Ring",
        costUsd: 1300,
        priority: 1,
      },
      {
        id: "metro-core-metro-dc",
        from: "metro-core",
        to: "metro-dc",
        kind: "leased-line",
        strength: "strong",
        distanceKm: 8,
        latencyMs: 5,
        jitterMs: 1,
        packetLossPct: 0,
        bandwidthMbps: 1200,
        carrier: "Civic Dark Fiber",
        costUsd: 2100,
        priority: 1,
      },
    ],
  },
  {
    id: "city-handoff-mesh",
    name: "City Handoff Mesh",
    summary:
      "A metro office and a service hub prefer the primary carrier mesh but can shift to a slower leased backup path.",
    devices: [
      {
        id: "harbor-campus",
        label: "Harbor Campus",
        kind: "access-node",
        status: "online",
        x: 140,
        y: 300,
        detail:
          "Harbor-side campus that consumes metro services and can switch to a slower backup path during provider degradation.",
        site: "Harbor Campus",
        region: "Harbor District",
        tier: "building",
        role: "site",
      },
      {
        id: "innovation-hub",
        label: "Innovation Hub",
        kind: "metro-core",
        status: "degraded",
        x: 430,
        y: 180,
        detail:
          "Metro aggregation site that still carries traffic but at reduced quality after a district maintenance event.",
        site: "Innovation Hub",
        region: "Innovation District",
        tier: "district",
        role: "site",
      },
      {
        id: "media-exchange",
        label: "Media Exchange",
        kind: "service-handoff",
        status: "online",
        x: 705,
        y: 165,
        detail:
          "Metro service handoff that stays reachable even when the primary provider path is degraded.",
        site: "Media Exchange",
        region: "Market Street",
        tier: "metro",
        role: "service",
      },
      {
        id: "city-archive",
        label: "City Archive",
        kind: "service-handoff",
        status: "online",
        x: 865,
        y: 340,
        detail:
          "Secondary metro service handoff available over the same carrier fabric for archive and backup workflows.",
        site: "City Archive",
        region: "Market Street",
        tier: "metro",
        role: "service",
      },
      {
        id: "provider-west",
        label: "Metro Mesh West",
        kind: "provider-handoff",
        status: "online",
        x: 285,
        y: 360,
        detail: "Primary west-side metro provider mesh for downtown service reachability.",
        site: "Metro Mesh West",
        region: "Harbor District",
        tier: "district",
        role: "transit",
      },
      {
        id: "provider-east",
        label: "Leased Backup East",
        kind: "provider-handoff",
        status: "online",
        x: 625,
        y: 355,
        detail: "Backup east-side leased provider path for reduced-capacity metro continuity.",
        site: "Leased Backup East",
        region: "Market Street",
        tier: "district",
        role: "transit",
      },
    ],
    connections: [
      {
        id: "harbor-campus-provider-west",
        from: "harbor-campus",
        to: "provider-west",
        kind: "metro-fiber",
        strength: "medium",
        distanceKm: 6,
        latencyMs: 6,
        jitterMs: 2,
        packetLossPct: 0.2,
        bandwidthMbps: 550,
        carrier: "Metro Mesh West",
        costUsd: 1400,
        priority: 1,
      },
      {
        id: "provider-west-innovation-hub",
        from: "provider-west",
        to: "innovation-hub",
        kind: "metro-fiber",
        strength: "strong",
        distanceKm: 5,
        latencyMs: 5,
        jitterMs: 2,
        packetLossPct: 0.1,
        bandwidthMbps: 550,
        carrier: "Metro Mesh West",
        costUsd: 1450,
        priority: 1,
      },
      {
        id: "innovation-hub-media-exchange",
        from: "innovation-hub",
        to: "media-exchange",
        kind: "metro-ethernet",
        strength: "strong",
        distanceKm: 4,
        latencyMs: 4,
        jitterMs: 1,
        packetLossPct: 0,
        bandwidthMbps: 600,
        carrier: "Metro Media Fabric",
        costUsd: 1600,
        priority: 1,
      },
      {
        id: "media-exchange-city-archive",
        from: "media-exchange",
        to: "city-archive",
        kind: "leased-line",
        strength: "medium",
        distanceKm: 3,
        latencyMs: 7,
        jitterMs: 2,
        packetLossPct: 0.2,
        bandwidthMbps: 420,
        carrier: "Archive Link",
        costUsd: 1250,
        priority: 1,
      },
      {
        id: "innovation-hub-provider-east",
        from: "innovation-hub",
        to: "provider-east",
        kind: "backup-link",
        strength: "medium",
        distanceKm: 9,
        latencyMs: 11,
        jitterMs: 4,
        packetLossPct: 0.4,
        bandwidthMbps: 280,
        carrier: "Leased Backup East",
        costUsd: 900,
        priority: 2,
      },
      {
        id: "provider-east-city-archive",
        from: "provider-east",
        to: "city-archive",
        kind: "backup-link",
        strength: "medium",
        distanceKm: 10,
        latencyMs: 13,
        jitterMs: 5,
        packetLossPct: 0.5,
        bandwidthMbps: 280,
        carrier: "Leased Backup East",
        costUsd: 1100,
        priority: 2,
      },
    ],
  },
]
