import { PanTopology } from "./pan.models"

export const PAN_TOPOLOGIES: PanTopology[] = [
  {
    id: "mobile-workbench",
    name: "Mobile Workbench",
    summary:
      "A laptop-centered personal workspace with short-range wireless accessories and a tethered phone.",
    devices: [
      {
        id: "laptop",
        label: "Laptop",
        kind: "laptop",
        status: "online",
        batteryLevel: 86,
        x: 350,
        y: 210,
        detail: "Primary compute node for work sessions and sync tasks.",
      },
      {
        id: "phone",
        label: "Phone",
        kind: "phone",
        status: "online",
        batteryLevel: 58,
        x: 170,
        y: 330,
        detail: "Provides tethering and personal messaging context.",
      },
      {
        id: "tablet",
        label: "Tablet",
        kind: "tablet",
        status: "idle",
        batteryLevel: 42,
        x: 570,
        y: 320,
        detail: "Secondary display and annotation device.",
      },
      {
        id: "headset",
        label: "Headset",
        kind: "headset",
        status: "online",
        batteryLevel: 71,
        x: 515,
        y: 110,
        detail: "Bluetooth audio peripheral used during calls.",
      },
      {
        id: "printer",
        label: "Printer",
        kind: "printer",
        status: "idle",
        x: 720,
        y: 190,
        detail: "Local print target shared over Wi-Fi Direct.",
      },
    ],
    connections: [
      {
        id: "laptop-headset",
        from: "laptop",
        to: "headset",
        kind: "bluetooth",
        strength: "strong",
      },
      { id: "laptop-tablet", from: "laptop", to: "tablet", kind: "wifi", strength: "strong" },
      { id: "phone-laptop", from: "phone", to: "laptop", kind: "usb", strength: "strong" },
      { id: "tablet-printer", from: "tablet", to: "printer", kind: "wifi", strength: "medium" },
    ],
  },
  {
    id: "travel-kit",
    name: "Travel Kit",
    summary:
      "A compact PAN focused on mobile connectivity, tethering, and battery-aware accessories.",
    devices: [
      {
        id: "travel-phone",
        label: "Phone",
        kind: "phone",
        status: "online",
        batteryLevel: 65,
        x: 280,
        y: 190,
        detail: "Acts as the hotspot anchor while travelling.",
      },
      {
        id: "travel-laptop",
        label: "Ultrabook",
        kind: "laptop",
        status: "online",
        batteryLevel: 48,
        x: 500,
        y: 250,
        detail: "Connected through tethering for low-friction internet access.",
      },
      {
        id: "travel-watch",
        label: "Watch",
        kind: "watch",
        status: "idle",
        batteryLevel: 39,
        x: 200,
        y: 70,
        detail: "Pairs with the phone for notifications and health telemetry.",
      },
      {
        id: "travel-headset",
        label: "Earbuds",
        kind: "headset",
        status: "online",
        batteryLevel: 53,
        x: 650,
        y: 110,
        detail: "Short-range audio device for calls in transit.",
      },
      {
        id: "travel-tablet",
        label: "Tablet",
        kind: "tablet",
        status: "offline",
        batteryLevel: 11,
        x: 665,
        y: 360,
        detail: "Low battery spare device, currently offline.",
      },
    ],
    connections: [
      {
        id: "travel-phone-watch",
        from: "travel-phone",
        to: "travel-watch",
        kind: "bluetooth",
        strength: "strong",
      },
      {
        id: "travel-phone-laptop",
        from: "travel-phone",
        to: "travel-laptop",
        kind: "tethering",
        strength: "strong",
      },
      {
        id: "travel-phone-headset",
        from: "travel-phone",
        to: "travel-headset",
        kind: "bluetooth",
        strength: "medium",
      },
      {
        id: "travel-laptop-tablet",
        from: "travel-laptop",
        to: "travel-tablet",
        kind: "wifi",
        strength: "weak",
      },
    ],
  },
  {
    id: "wearable-stack",
    name: "Wearable Stack",
    summary: "A personal network centered on wearables and low-power companion devices.",
    devices: [
      {
        id: "wear-phone",
        label: "Phone",
        kind: "phone",
        status: "online",
        batteryLevel: 78,
        x: 395,
        y: 220,
        detail: "Hub for app sync, identity, and notifications.",
      },
      {
        id: "wear-watch",
        label: "Watch",
        kind: "watch",
        status: "online",
        batteryLevel: 88,
        x: 250,
        y: 110,
        detail: "Receives notifications and health metrics.",
      },
      {
        id: "wear-headset",
        label: "Headset",
        kind: "headset",
        status: "idle",
        batteryLevel: 44,
        x: 575,
        y: 120,
        detail: "Audio endpoint paired with the phone.",
      },
      {
        id: "wear-tablet",
        label: "Tablet",
        kind: "tablet",
        status: "idle",
        batteryLevel: 67,
        x: 600,
        y: 350,
        detail: "Secondary screen for dashboards and media.",
      },
      {
        id: "wear-hotspot",
        label: "Hotspot",
        kind: "hotspot",
        status: "online",
        x: 180,
        y: 320,
        detail: "Portable uplink for devices that need internet access.",
      },
    ],
    connections: [
      {
        id: "wear-phone-watch",
        from: "wear-phone",
        to: "wear-watch",
        kind: "bluetooth",
        strength: "strong",
      },
      {
        id: "wear-phone-headset",
        from: "wear-phone",
        to: "wear-headset",
        kind: "bluetooth",
        strength: "strong",
      },
      {
        id: "wear-phone-tablet",
        from: "wear-phone",
        to: "wear-tablet",
        kind: "wifi",
        strength: "medium",
      },
      {
        id: "wear-hotspot-phone",
        from: "wear-hotspot",
        to: "wear-phone",
        kind: "wifi",
        strength: "medium",
      },
    ],
  },
]
